#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    using NuGetGallery;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/Account.cshtml")]
    public class Account : System.Web.Mvc.WebViewPage<User>
    {
        public Account()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Users\Account.cshtml"
  
    ViewBag.Tab = "Contribute";


            
            #line default
            #line hidden
WriteLiteral("\n<h1 class=\"page-heading\">My Account</h1>\n\n<section id=\"actions\">\n    <h1>Actions" +
"</h1>\n    <ul>\n        <li id=\"uploadPackage\">\n            <h2><a href=\"");


            
            #line 12 "..\..\Views\Users\Account.cshtml"
                    Write(Url.UploadPackage());

            
            #line default
            #line hidden
WriteLiteral(@""">Upload Package</a></h2>
            <p>
                Upload and publish your package for other NuGet users to download and enjoy. 
                You can upload multiple revisions of the same package, as long as the version 
                is different.
            </p>
        </li>
        <li id=""managePackages"">
            <h2><a href=""");


            
            #line 20 "..\..\Views\Users\Account.cshtml"
                    Write(Url.Action(MVC.Users.Packages()));

            
            #line default
            #line hidden
WriteLiteral("\">Manage My Packages</a></h2>\n            <p>Edit package details or Remove packa" +
"ges that you have previously uploaded.</p>\n        </li>\n        <li id=\"editPro" +
"file\">\n            <h2><a href=\"");


            
            #line 24 "..\..\Views\Users\Account.cshtml"
                    Write(Url.Action(MVC.Users.Edit()));

            
            #line default
            #line hidden
WriteLiteral("\">Edit Profile</a></h2>\n            <p>Edit your public profile.</p>\n        </li" +
">\n        <li id=\"changePassword\">\n            <h2><a href=\"");


            
            #line 28 "..\..\Views\Users\Account.cshtml"
                    Write(Url.Action(MVC.Users.ChangePassword()));

            
            #line default
            #line hidden
WriteLiteral(@""">Change Password</a></h2>
            <p>Change your password.</p>
        </li>
    </ul>
</section>



<section id=""apiKey"">
<h1>API Key</h1>
    <p>
        Your API key provides you with a token that identifies you to the gallery. 
        Keep this a secret. You can always regenerate your key at any time (invalidating 
        previous keys) if your token is accidentally revealed. The 
        <a href=""http://nuget.codeplex.com/"">NuGet</a> command-line utility allows you to 
        submit a NuGet package to the gallery, and you would pass you token like this:
    </p>
    
    <div id=""generateKey"">
        <h2>Your API key is:</h2>
        
        <div>
            <p id=""key"">");


            
            #line 50 "..\..\Views\Users\Account.cshtml"
                   Write(Model.ApiKey);

            
            #line default
            #line hidden
WriteLiteral("</p>\n\n            <fieldset class=\"form\">\n                <legend>Generate New AP" +
"I Key</legend>\n");


            
            #line 54 "..\..\Views\Users\Account.cshtml"
                 using(Html.BeginForm("GenerateApiKey", "Users", FormMethod.Post)){
                    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Users\Account.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Users\Account.cshtml"
                                            

            
            #line default
            #line hidden
WriteLiteral("                    <input type=\"submit\" value=\"Generate New API Key\" />\n");


            
            #line 57 "..\..\Views\Users\Account.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </fieldset>\n\n            <h2>Example usage:</h2>\n            <p><code" +
">nuget.exe push MyPackage.1.0.nupkg ");


            
            #line 61 "..\..\Views\Users\Account.cshtml"
                                                   Write(Model.ApiKey);

            
            #line default
            #line hidden
WriteLiteral("</code></p>\n        \n        </div>\n\n        <div id=\"overlayWrapper\" title=\"Clic" +
"k to show API Key\">\n            Your key is hidden for privacy, click to show.\n " +
"       </div>\n    </div>\n</section>\n\n");


DefineSection("BottomScripts", () => {

WriteLiteral("\n    <script>\n        $(function () {\n            $(\"#overlayWrapper\").click(func" +
"tion () {\n                $(\"#overlayWrapper\").fadeOut();\n                return" +
" false;\n            });\n        });\n    </script>\n");


});


        }
    }
}
#pragma warning restore 1591
