#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Users
{
    using System.Web.Mvc;
    using NuGetGallery;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/Account.cshtml")]
    public class Account : System.Web.Mvc.WebViewPage<User>
    {
        public Account()
        {
        }
        public override void Execute()
        {



#line 2 "..\..\Views\Users\Account.cshtml"

            ViewBag.Tab = "Contribute";
            Layout = "~/Views/Shared/TwoColumnLayout.cshtml";



#line default
#line hidden
            WriteLiteral("\r\n");


            DefineSection("LeftNav", () =>
            {

                WriteLiteral("\r\n    <img src=\"");



#line 8 "..\..\Views\Users\Account.cshtml"
                Write(Links.Content.Images.contribGraphic_png);


#line default
#line hidden
                WriteLiteral("\" alt=\"The unknown user image\" />\r\n");


            });

            WriteLiteral("                \r\n\r\n");


            DefineSection("ContentHeader", () =>
            {

                WriteLiteral("\r\n    <h2>My Account</h2>\r\n");



#line 13 "..\..\Views\Users\Account.cshtml"
                if (TempData.ContainsKey("Message"))
                {


#line default
#line hidden
                    WriteLiteral("        <div id=\"messages\">\r\n            <div class=\"zone zone-messages\">\r\n      " +
                    "          <div class=\"message message-Information\">");



#line 16 "..\..\Views\Users\Account.cshtml"
                    Write(TempData["Message"]);


#line default
#line hidden
                    WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n");



#line 19 "..\..\Views\Users\Account.cshtml"
                }


#line default
#line hidden

            });

            WriteLiteral("\r\n<h3>Actions</h3>\r\n<section class=\"add-new\">\r\n    <h4><a href=\"");



#line 23 "..\..\Views\Users\Account.cshtml"
            Write(Url.UploadPackage());


#line default
#line hidden
            WriteLiteral(@""">Upload Package</a></h4>
    <p>
        Upload and publish your package for other NuGet users to download and enjoy. 
        You can upload multiple revisions of the same package, as long as the version 
        is different.
    </p>
</section>
<section>
    <h5><a href=""");



#line 31 "..\..\Views\Users\Account.cshtml"
            Write(Url.Action(MVC.Users.Packages()));


#line default
#line hidden
            WriteLiteral("\">Manage My Contributions</a></h5>\r\n    <p>Edit contribution details or Remove co" +
            "ntributions that you have previously uploaded.</p>\r\n</section>\r\n<section>\r\n    <" +
            "h5><a href=\"");



#line 35 "..\..\Views\Users\Account.cshtml"
            Write(Url.Action(MVC.Users.Edit()));


#line default
#line hidden
            WriteLiteral("\">Edit Profile</a></h5>\r\n</section>\r\n<section>\r\n    <h5><a href=\"");



#line 38 "..\..\Views\Users\Account.cshtml"
            Write(Url.Action(MVC.Users.ChangePassword()));


#line default
#line hidden
            WriteLiteral(@""">Change Password</a></h5>
</section>

<section>
<h3>Access Key</h3>
    <p>
        Your access key provides you with a token that identifies you to the gallery. 
        Keep this a secret. You can always regenerate your key at any time (invaldating 
        previous keys) if your token is accidentally revealed. The 
        <a href=""http://nuget.codeplex.com/"">NuGet</a> command-line utility allows you to 
        submit a nuget package to the gallery, and you would pass you token like this:
    </p>
    <p><code>nuget push MyPackage.1.0.nupkg ");



#line 50 "..\..\Views\Users\Account.cshtml"
            Write(Model.ApiKey);


#line default
#line hidden
            WriteLiteral("</code></p>\r\n    <div style=\"border: 1px solid #ccc;padding:0 15px 15px;width:350" +
            "px;margin-top:20px;\">\r\n        <h4>Your access key is: </h4>\r\n        <p id=\"acc" +
            "essKey\">");



#line 53 "..\..\Views\Users\Account.cshtml"
            Write(Model.ApiKey);


#line default
#line hidden
            WriteLiteral("</p>\r\n        <form Id=\"generateKeyForm\" action=\"");



#line 54 "..\..\Views\Users\Account.cshtml"
            Write(Url.Action(MVC.Users.GenerateApiKey()));


#line default
#line hidden
            WriteLiteral("\" method=\"post\">            \r\n            ");



#line 55 "..\..\Views\Users\Account.cshtml"
            Write(Html.AntiForgeryToken());


#line default
#line hidden
            WriteLiteral("\r\n            <input id=\"generateKeyButton\" type=\"submit\" value=\"Generate New Key" +
            "\" singleClickButton=\"true\" />\r\n        </form>\r\n    </div>\r\n</section>");


        }
    }
}
#pragma warning restore 1591
