#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Users\Account.cshtml"
    using NuGetGallery;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/Account.cshtml")]
    public class Account : System.Web.Mvc.WebViewPage<User>
    {
        public Account()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Users\Account.cshtml"
  
    ViewBag.Tab = "Contribute";
    Layout = "~/Views/Shared/TwoColumnLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\n");


DefineSection("LeftNav", () => {

WriteLiteral("\n    <img src=\"");


            
            #line 9 "..\..\Views\Users\Account.cshtml"
         Write(Links.Content.Images.contribGraphic_png);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Upload package graphic\" />\n");


});

WriteLiteral("                \n\n");


DefineSection("ContentHeader", () => {

WriteLiteral("\n    <h2>My Account</h2>    \n");


});

WriteLiteral("\n<h3>Actions</h3>\n<section class=\"add-new\">\n    <h4><a href=\"");


            
            #line 17 "..\..\Views\Users\Account.cshtml"
            Write(Url.UploadPackage());

            
            #line default
            #line hidden
WriteLiteral(@""">Upload Package</a></h4>
    <p>
        Upload and publish your package for other NuGet users to download and enjoy. 
        You can upload multiple revisions of the same package, as long as the version 
        is different.
    </p>
</section>
<section>
    <h5><a href=""");


            
            #line 25 "..\..\Views\Users\Account.cshtml"
            Write(Url.Action(MVC.Users.Packages()));

            
            #line default
            #line hidden
WriteLiteral("\">Manage My Contributions</a></h5>\n    <p>Edit contribution details or Remove con" +
"tributions that you have previously uploaded.</p>\n</section>\n<section>\n    <h5><" +
"a href=\"");


            
            #line 29 "..\..\Views\Users\Account.cshtml"
            Write(Url.Account(AccountAction.ChangePassword));

            
            #line default
            #line hidden
WriteLiteral(@""">Change Password</a></h5>
</section>

<section>
<h3>Access Key</h3>
    <p>
        Your access key provides you with a token that identifies you to the gallery. 
        Keep this a secret. You can always regenerate your key at any time (invaldating 
        previous keys) if your token is accidentally revealed. The 
        <a href=""http://nuget.codeplex.com/"">NuGet</a> command-line utility allows you to 
        submit a nuget package to the gallery, and you would pass you token like this:
    </p>
    <p><code>nuget push MyPackage.1.0.nupkg ");


            
            #line 41 "..\..\Views\Users\Account.cshtml"
                                       Write(Model.ApiKey);

            
            #line default
            #line hidden
WriteLiteral("</code></p>\n    <div style=\"border: 1px solid #ccc;padding:0 15px 15px;width:350p" +
"x;margin-top:20px;\">\n        <h4>Your access key is: </h4>\n        <p id=\"access" +
"Key\">");


            
            #line 44 "..\..\Views\Users\Account.cshtml"
                     Write(Model.ApiKey);

            
            #line default
            #line hidden
WriteLiteral("</p>\n        <form Id=\"generateKeyForm\" action=\"");


            
            #line 45 "..\..\Views\Users\Account.cshtml"
                                      Write(Url.Action(MVC.Users.GenerateApiKey()));

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\">            \n            ");


            
            #line 46 "..\..\Views\Users\Account.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n            <input id=\"generateKeyButton\" type=\"submit\" value=\"Generate New Key\"" +
" singleClickButton=\"true\" />\n        </form>\n    </div>\n</section>");


        }
    }
}
#pragma warning restore 1591
