#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    
    #line 1 "..\..\Views\Users\Profiles.cshtml"
    using NuGetGallery;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/Profiles.cshtml")]
    public class Profiles : System.Web.Mvc.WebViewPage<UserProfileModel>
    {
        public Profiles()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Users\Profiles.cshtml"
  
    ViewBag.Title = @Model.Username;
    Layout = "~/Views/Shared/TwoColumnLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


DefineSection("SideColumn", () => {

WriteLiteral("\r\n    ");


            
            #line 10 "..\..\Views\Users\Profiles.cshtml"
Write(ViewHelpers.GravatarImage(Model.EmailAddress, Model.Username, 128));

            
            #line default
            #line hidden
WriteLiteral("\r\n     <div id=\"stats\">\r\n        <div class=\"stat\">\r\n            <p class=\"stat-n" +
"umber\">");


            
            #line 13 "..\..\Views\Users\Profiles.cshtml"
                              Write(Model.Packages.Count.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            <p class=\"stat-label\">Packages</p>\r\n        </div>\r\n        <di" +
"v class=\"stat\">\r\n            <p class=\"stat-number\">");


            
            #line 17 "..\..\Views\Users\Profiles.cshtml"
                              Write(Model.TotalPackageDownloadCount.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            <p class=\"stat-label\">Downloads of ");


            
            #line 18 "..\..\Views\Users\Profiles.cshtml"
                                          Write(Model.Username);

            
            #line default
            #line hidden
WriteLiteral("\'s packages</p>\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n<h1>");


            
            #line 23 "..\..\Views\Users\Profiles.cshtml"
Write(Model.Username);

            
            #line default
            #line hidden
WriteLiteral("\'s Profile</h1>\r\n\r\n<h2>Packages</h2>\r\n<ul id=\"searchResults\">\r\n");


            
            #line 27 "..\..\Views\Users\Profiles.cshtml"
     foreach (var package in Model.Packages) {

            
            #line default
            #line hidden
WriteLiteral("    <li>\r\n        <section class=\"package\">\r\n            <div class=\"side\">\r\n    " +
"            <a href=\"");


            
            #line 31 "..\..\Views\Users\Profiles.cshtml"
                    Write(Url.Package(package));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"View more about ");


            
            #line 31 "..\..\Views\Users\Profiles.cshtml"
                                                                  Write(package.Title);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <img src=\"");


            
            #line 32 "..\..\Views\Users\Profiles.cshtml"
                          Write(package.IconUrl ?? Links.Content.Images.packageDefaultIcon_50x50_png);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 32 "..\..\Views\Users\Profiles.cshtml"
                                                                                                       Write(package.Id);

            
            #line default
            #line hidden
WriteLiteral(" icon\" onerror=\"this.src=\'");


            
            #line 32 "..\..\Views\Users\Profiles.cshtml"
                                                                                                                                            Write(Links.Content.Images.packageDefaultIcon_50x50_png);

            
            #line default
            #line hidden
WriteLiteral("\';\" />\r\n                </a>\r\n            </div>\r\n            <div class=\"main\">\r" +
"\n                <h1><a href=\"");


            
            #line 36 "..\..\Views\Users\Profiles.cshtml"
                        Write(Url.Package(package));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 36 "..\..\Views\Users\Profiles.cshtml"
                                               Write(package.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></h1>\r\n                \r\n                <p>\r\n");


            
            #line 39 "..\..\Views\Users\Profiles.cshtml"
                     if (String.IsNullOrEmpty(package.Description) || package.Description.Length < 350) {
                        
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Users\Profiles.cshtml"
                   Write(package.Description);

            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Users\Profiles.cshtml"
                                            
                    }
                    else {
                        
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Users\Profiles.cshtml"
                   Write(package.Description.Substring(0, 350));

            
            #line default
            #line hidden

WriteLiteral("... ");



WriteLiteral("<a href=\"");


            
            #line 43 "..\..\Views\Users\Profiles.cshtml"
                                                                                   Write(Url.Package(package));

            
            #line default
            #line hidden
WriteLiteral("\">More information</a>\r\n");


            
            #line 44 "..\..\Views\Users\Profiles.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </p>\r\n\r\n                <footer>\r\n                    <p class=\"d" +
"ownloads\">\r\n                        ");


            
            #line 49 "..\..\Views\Users\Profiles.cshtml"
                   Write(package.TotalDownloadCount.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" downloads\r\n                    </p>\r\n                </footer>\r\n            </di" +
"v>\r\n        </section>\r\n    </li>\r\n");


            
            #line 55 "..\..\Views\Users\Profiles.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");


        }
    }
}
#pragma warning restore 1591
