#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    
    #line 1 "..\..\Views\Users\Thanks.cshtml"
    using NuGetGallery;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/Thanks.cshtml")]
    public class Thanks : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Thanks()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n\r\n\r\n");


            
            #line 5 "..\..\Views\Users\Thanks.cshtml"
 if (!Request.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("    <h1 class=\"page-heading\">\r\n        Thanks for registering</h1>\r\n");


            
            #line 8 "..\..\Views\Users\Thanks.cshtml"
}
else {

            
            #line default
            #line hidden
WriteLiteral("    <h1 class=\"page-heading\">\r\n        You are all set</h1>\r\n");


            
            #line 12 "..\..\Views\Users\Thanks.cshtml"
}

            
            #line default
            #line hidden

            
            #line 13 "..\..\Views\Users\Thanks.cshtml"
 if (!Request.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("    <strong>But you\'re not done yet!</strong>\r\n");


            
            #line 15 "..\..\Views\Users\Thanks.cshtml"
    if (Request.IsLocal) {

            
            #line default
            #line hidden
WriteLiteral("        <p class=\"message\">\r\n            Pssst! I see you\'re running this in a de" +
"velopment environment. <strong>Check the <em>\r\n                \\App_Data\\Mail</e" +
"m> folder for the email</strong>.\r\n        </p>\r\n");


            
            #line 20 "..\..\Views\Users\Thanks.cshtml"
    } else {

            
            #line default
            #line hidden
WriteLiteral("        <p>\r\n            An email with instructions on how to activate your accou" +
"nt is on its way to you.\r\n        </p>\r\n");


            
            #line 24 "..\..\Views\Users\Thanks.cshtml"
    }
}
else {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        It looks like you\'ve already confirmed your account and are good" +
" to go.\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        Click on the <em>Upload package</em> link in the menu to start u" +
"ploading packages.\r\n    </p>\r\n");


            
            #line 33 "..\..\Views\Users\Thanks.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
