#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Packages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    using NuGetGallery;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Packages/ContactOwners.cshtml")]
    public class ContactOwners : System.Web.Mvc.WebViewPage<ContactOwnersViewModel>
    {
        public ContactOwners()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Packages\ContactOwners.cshtml"
  
    ViewBag.Tab = "Packages";
    Layout = "~/Views/Shared/TwoColumnLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("LeftNav", () => {

WriteLiteral("\r\n    <img src=\"");


            
            #line 8 "..\..\Views\Packages\ContactOwners.cshtml"
         Write(Links.Content.Images.sendMessageGraphic_png);

            
            #line default
            #line hidden
WriteLiteral("\" style=\"padding-left: 55px\" />\r\n");


});

WriteLiteral("    \r\n\r\n");


DefineSection("ContentHeader", () => {

WriteLiteral("            \r\n    <h2>Contact the Owners of <em>");


            
            #line 12 "..\..\Views\Packages\ContactOwners.cshtml"
                             Write(Model.PackageId);

            
            #line default
            #line hidden
WriteLiteral("</em></h2>\r\n");


});

WriteLiteral("\r\n\r\n<div class=\"description\">\r\n<p>\r\n    By submitting this form, you agree to <st" +
"rong>disclose your email address</strong> \r\n    to the package owners listed bel" +
"ow so they can reply to you.\r\n</p>\r\n</div> \r\n<div id=\"form\">\r\n    <form action=\"" +
"");


            
            #line 22 "..\..\Views\Packages\ContactOwners.cshtml"
             Write(Url.Current());

            
            #line default
            #line hidden
WriteLiteral("\" id=\"contactOwnersForm\" method=\"post\">\r\n        <label style=\"padding-left: 20px" +
";\">\r\n            To: ");


            
            #line 24 "..\..\Views\Packages\ContactOwners.cshtml"
           Write(ViewHelpers.OwnersGravatar(Model.Owners, 24, Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </label>\r\n        <div>\r\n            ");


            
            #line 27 "..\..\Views\Packages\ContactOwners.cshtml"
       Write(Html.LabelFor(m => m.Message));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                \r\n            ");


            
            #line 29 "..\..\Views\Packages\ContactOwners.cshtml"
       Write(Html.TextAreaFor(m => m.Message, 10, 60, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div style=\"display: block;\">\r\n                ");


            
            #line 31 "..\..\Views\Packages\ContactOwners.cshtml"
           Write(Html.ValidationMessageFor(m => m.Message));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        ");


            
            #line 34 "..\..\Views\Packages\ContactOwners.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <input id=\"contactOwnersButton\" type=\"submit\" value=\"Send\" singleclickb" +
"utton=\"true\" />\r\n    </form>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
