#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Packages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NuGetGallery;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Packages/ContactOwners.cshtml")]
    public class ContactOwners : System.Web.Mvc.WebViewPage<ContactOwnersViewModel>
    {
        public ContactOwners()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Packages\ContactOwners.cshtml"
  
    ViewBag.Tab = "Packages";
    Layout = "~/Views/Shared/TwoColumnLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\n");


DefineSection("LeftNav", () => {

WriteLiteral("\n    <img src=\"");


            
            #line 8 "..\..\Views\Packages\ContactOwners.cshtml"
         Write(Links.Content.Images.sendMessageGraphic_png);

            
            #line default
            #line hidden
WriteLiteral("\" style=\"padding-left: 55px\" />\n");


});

WriteLiteral("    \n\n");


DefineSection("ContentHeader", () => {

WriteLiteral("            \n    <h2>Contact Owners</h2>\n");


});

WriteLiteral("\n    \n<p>\n    Use this form to contact the owners of <strong>\"");


            
            #line 16 "..\..\Views\Packages\ContactOwners.cshtml"
                                               Write(Model.PackageId);

            
            #line default
            #line hidden
WriteLiteral("\"</strong>. \n</p>\n<p>\n    By submitting this form, you agree to <strong>disclose " +
"your email address</strong> \n    to the package owners listed below so they can " +
"reply to you.\n</p>\n<div id=\"form\">\n    <form action=\"");


            
            #line 23 "..\..\Views\Packages\ContactOwners.cshtml"
             Write(Url.Current());

            
            #line default
            #line hidden
WriteLiteral("\" id=\"contactOwnersForm\" method=\"post\">\n        <label style=\"padding-left: 20px;" +
"\">\n            To: ");


            
            #line 25 "..\..\Views\Packages\ContactOwners.cshtml"
           Write(Model.Owners.Flatten(item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

            
            #line default
            #line hidden

WriteLiteralTo(@__razor_template_writer, "<strong><a href=\"");


            
            #line 25 "..\..\Views\Packages\ContactOwners.cshtml"
                       WriteTo(@__razor_template_writer, Url.Search(item.Username));

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "\" title=\"Search packages for this user\">");


            
            #line 25 "..\..\Views\Packages\ContactOwners.cshtml"
                                                                                         WriteTo(@__razor_template_writer, item.Username);

            
            #line default
            #line hidden
WriteLiteralTo(@__razor_template_writer, "</a></strong>");


            
            #line 25 "..\..\Views\Packages\ContactOwners.cshtml"
                                                                                                                                                   })));

            
            #line default
            #line hidden
WriteLiteral("\n        </label>\n        <div>\n            ");


            
            #line 28 "..\..\Views\Packages\ContactOwners.cshtml"
       Write(Html.LabelFor(m => m.Message));

            
            #line default
            #line hidden
WriteLiteral("\n                                \n            ");


            
            #line 30 "..\..\Views\Packages\ContactOwners.cshtml"
       Write(Html.TextAreaFor(m => m.Message, 10, 60, null));

            
            #line default
            #line hidden
WriteLiteral("\n            <div style=\"display: block;\">\n                ");


            
            #line 32 "..\..\Views\Packages\ContactOwners.cshtml"
           Write(Html.ValidationMessageFor(m => m.Message));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n        ");


            
            #line 35 "..\..\Views\Packages\ContactOwners.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n        <input id=\"contactOwnersButton\" type=\"submit\" value=\"Send\" singleclickbu" +
"tton=\"true\" />\n    </form>\n</div>\n");


        }
    }
}
#pragma warning restore 1591
