#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Packages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    using NuGetGallery;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Packages/Delete.cshtml")]
    public class Delete : System.Web.Mvc.WebViewPage<DisplayPackageViewModel>
    {
        public Delete()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Packages\Delete.cshtml"
  
    ViewBag.Tab = "Packages";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h1 class=\"page-heading\"><em>");


            
            #line 6 "..\..\Views\Packages\Delete.cshtml"
                        Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 6 "..\..\Views\Packages\Delete.cshtml"
                                     Write(Model.Version);

            
            #line default
            #line hidden
WriteLiteral(@"</em> Listing</h1>
<p class=""message"">
    Permanently deleting packages is not supported, but you can control how they are listed.
</p>
<p>
    Unlisting a package hides the package from search results and all NuGet commands, but packages 
    are still available for download. For example, they can still be downloaded as dependencies to 
    other packages.
</p>

");


            
            #line 16 "..\..\Views\Packages\Delete.cshtml"
 using (Html.BeginForm()) {

            
            #line default
            #line hidden
WriteLiteral("    <fieldset id=\"unlist-form\" class=\"form\">\r\n        <legend>Edit ");


            
            #line 18 "..\..\Views\Packages\Delete.cshtml"
                Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral(" Package</legend>\r\n        ");


            
            #line 19 "..\..\Views\Packages\Delete.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"form-field\">\r\n            ");


            
            #line 21 "..\..\Views\Packages\Delete.cshtml"
       Write(Html.EditorFor(package => package.Listed));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <label for=\"Listed\" class=\"checkbox\">\r\n                List ");


            
            #line 23 "..\..\Views\Packages\Delete.cshtml"
                Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 23 "..\..\Views\Packages\Delete.cshtml"
                             Write(Model.Version);

            
            #line default
            #line hidden
WriteLiteral(@" in search results.
            </label>
        </div>

        <p>
            Unchecking this box means your package cannot be installed directly and it will 
            not show up in search results.
        </p>

        <input type=""submit"" value=""Save"" title=""Save Changes"" />
        <a class=""cancel"" href=""");


            
            #line 33 "..\..\Views\Packages\Delete.cshtml"
                           Write(Url.Action("DisplayPackage"));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Cancel Changes and go back to package page.\">Cancel</a>\r\n    </fieldset>" +
"\r\n");


            
            #line 35 "..\..\Views\Packages\Delete.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"
<h2>Why can&#8217;t I delete my package?</h2>
<p>
    Our policy is to only permanently delete NuGet packages that really need it, such as 
    packages that contain passwords, malicious/harmful code, etc. This policy is very similar 
    to the policies employed by other package managers such as 
    <a href=""http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem"" title="""">Ruby Gems</a>.</p>
<p>
    Unlisting the package will remove the package from 
    being available in the NuGet. The package is still available for download as a dependency for 
    three main reasons.
</p>
<ul>
    <li>
        Other packages may depend on that package. Those packages might not necessarily be in this gallery.
    </li>
    <li>
        Ensures that folks <a href=""http://docs.nuget.org/docs/workflows/using-nuget-without-committing-packages"">using NuGet without committing packages (package restore)</a> 
        will not be broken.
    </li>
    <li>
        Helps ensure that important community owned packages are not mass deleted.
    </li>
</ul>
<p>
If you need the package permanently removed, click on the <a href=""");


            
            #line 61 "..\..\Views\Packages\Delete.cshtml"
                                                              Write(Url.Action(MVC.Packages.ReportAbuse(Model.Id, Model.Version)));

            
            #line default
            #line hidden
WriteLiteral(@""" title=""Report Abuse"">Report Abuse</a> link and we'll take care 
of it for you. PLEASE ONLY DO THIS IF THERE IS AN URGENT PROBLEM WITH THE PACKAGE. 
(Passwords, malicious code, etc). Even if you remove it, it&#8217;s prudent to immediately 
reset any passwords/sensitive data you accidentally pushed instead of waiting for us to delete 
the package.
</p>");


        }
    }
}
#pragma warning restore 1591
