#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Packages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    using NuGetGallery;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Packages/DisplayPackage.cshtml")]
    public class DisplayPackage : System.Web.Mvc.WebViewPage<DisplayPackageViewModel>
    {
        public DisplayPackage()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Packages\DisplayPackage.cshtml"
  
    ViewBag.Tab = "Packages";


            
            #line default
            #line hidden
WriteLiteral("<div id=\"layout-main\" class=\"group\">\r\n    <div id=\"layout-content\" class=\"group\">" +
"\r\n");


            
            #line 7 "..\..\Views\Packages\DisplayPackage.cshtml"
         if (TempData.ContainsKey("Message")) {

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"messages\">\r\n                <div class=\"zone zone-messages\">" +
"\r\n                    <div class=\"message message-Information\">");


            
            #line 10 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                        Write(TempData["Message"]);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>\r\n");


            
            #line 13 "..\..\Views\Packages\DisplayPackage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"        <div id=""content"" class=""group"">
            <div class=""zone zone-content"">
                <section class=""packageItemDetail icon"">
                    <div id=""thumbnails"">
                        <div class=""packageLogo"">
                            <img src=""");


            
            #line 19 "..\..\Views\Packages\DisplayPackage.cshtml"
                                  Write(Model.IconUrl ?? @Links.Content.Images.packageDefaultIcon_png);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Icon for package ");


            
            #line 19 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                         Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        </div>\r\n                    </div>\r\n               " +
"     <div>\r\n                        <header>\r\n                            <div c" +
"lass=\"title\">\r\n                                <h2>");


            
            #line 25 "..\..\Views\Packages\DisplayPackage.cshtml"
                               Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                                <h3>\r\n                                    " +
"");


            
            #line 27 "..\..\Views\Packages\DisplayPackage.cshtml"
                               Write(Model.Version);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 28 "..\..\Views\Packages\DisplayPackage.cshtml"
                                     if (Model.Prerelease) { 

            
            #line default
            #line hidden
WriteLiteral("                                    <span class=\"prerelease\">Prerelease</span>\r\n");


            
            #line 30 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    }
                                    else if (Model.LatestVersion) {

            
            #line default
            #line hidden
WriteLiteral("                                        <span class=\"latest\">Latest Version</span" +
">\r\n");


            
            #line 33 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </h3>\r\n                            </div>\r\n      " +
"                      <div class=\"description\">\r\n                               " +
" <p>\r\n                                    ");


            
            #line 38 "..\..\Views\Packages\DisplayPackage.cshtml"
                               Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </p>\r\n                                <p>\r\n    " +
"                                To install ");


            
            #line 41 "..\..\Views\Packages\DisplayPackage.cshtml"
                                          Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral(@", run the following command in the 
                                    <a href=""http://docs.nuget.org/docs/start-here/using-the-package-manager-console"">Package Manager Console</a>:
                                    <div class=""commandWrapper"">
                                        <div class=""commandPrompt"">
                                            <p class=""command"">PM&gt; Install-Package ");


            
            #line 45 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                 Write(Model.Id);

            
            #line default
            #line hidden

            
            #line 45 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                 if (!Model.LatestVersion) {
            
            #line default
            #line hidden
WriteLiteral(" -Version ");


            
            #line 45 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                       Write(Model.Version);

            
            #line default
            #line hidden

            
            #line 45 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                                                 }
            
            #line default
            #line hidden
WriteLiteral(@"</p>
                                        </div>
                                    </div>
                                </p>
                            </div>
                        </header>
                                        
                        <h4 class=""details-header"">Packages details</h4>
");


            
            #line 53 "..\..\Views\Packages\DisplayPackage.cshtml"
                         if (Model.IsOwner(User)) {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"package-owner-actions\">\r\n                " +
"                <ul>\r\n                                    <li><a class=\"edit\" hr" +
"ef=\"");


            
            #line 56 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                         Write(Url.EditPackage(Model));

            
            #line default
            #line hidden
WriteLiteral("\">Edit</a></li>\r\n                                    <li><a class=\"manage-owners\"" +
" href=\"");


            
            #line 57 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                  Write(Url.ManagePackageOwners(Model));

            
            #line default
            #line hidden
WriteLiteral("\">Manage Owners</a></li>\r\n                                    <li><a href=\"");


            
            #line 58 "..\..\Views\Packages\DisplayPackage.cshtml"
                                            Write(Url.DeletePackage(Model));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">Delete</a></li>\r\n                                </ul>\r\n        " +
"                    </div>\r\n");


            
            #line 61 "..\..\Views\Packages\DisplayPackage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <ul class=\"links\">\r\n");


            
            #line 63 "..\..\Views\Packages\DisplayPackage.cshtml"
                             if (!String.IsNullOrEmpty(Model.ProjectUrl)) {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a href=\"");


            
            #line 64 "..\..\Views\Packages\DisplayPackage.cshtml"
                                        Write(Model.ProjectUrl);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Visit the project site to learn more about this package\">\r\n             " +
"                       Project site</a></li>\r\n");


            
            #line 66 "..\..\Views\Packages\DisplayPackage.cshtml"
                            }

            
            #line default
            #line hidden

            
            #line 67 "..\..\Views\Packages\DisplayPackage.cshtml"
                             if (!String.IsNullOrEmpty(Model.LicenseUrl)) {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a href=\"");


            
            #line 68 "..\..\Views\Packages\DisplayPackage.cshtml"
                                        Write(Model.LicenseUrl);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Make sure you agree with the license\">License</a></li>\r\n");


            
            #line 69 "..\..\Views\Packages\DisplayPackage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <li><a href=\"");


            
            #line 70 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    Write(Url.Action(MVC.Packages.ReportAbuse(Model.Id, Model.Version)));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Report Abuse\">Report Abuse</a></li>\r\n                            <li><a " +
"href=\"");


            
            #line 71 "..\..\Views\Packages\DisplayPackage.cshtml"
                                    Write(Url.Action(MVC.Packages.ContactOwners(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\">Contact Owners</a></li>\r\n                        </ul>\r\n\r\n                     " +
"   ");


            
            #line 74 "..\..\Views\Packages\DisplayPackage.cshtml"
                   Write(Html.Partial("_PackageDetailsTable", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        <div class=\"stats\">\r\n                            <spa" +
"n class=\"downloads\">\r\n                                <strong>");


            
            #line 78 "..\..\Views\Packages\DisplayPackage.cshtml"
                                   Write(Model.TotalDownloadCount);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                <label>total downloads</label>\r\n      " +
"                      </span>\r\n                            <span class=\"download" +
"s\">\r\n                                <strong>");


            
            #line 82 "..\..\Views\Packages\DisplayPackage.cshtml"
                                   Write(Model.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                <label>for this version</label>\r\n     " +
"                       </span>\r\n                        </div>\r\n\r\n              " +
"          <h4 class=\"details-header\">Dependencies</h4>\r\n");


            
            #line 88 "..\..\Views\Packages\DisplayPackage.cshtml"
                         if (Model.Dependencies.Any()) {

            
            #line default
            #line hidden
WriteLiteral(@"                            <table class=""packages dependencies"">
                                <thead>
                                    <tr class=""header"">
                                        <th style=""width: 10%;"">Id</th>
                                        <th class=""version"">Version Range</th>
                                    </tr>
                                </thead>
");


            
            #line 96 "..\..\Views\Packages\DisplayPackage.cshtml"
                             foreach (var dependency in Model.Dependencies) {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td sty" +
"le=\"width: auto;\"><a href=\"");


            
            #line 98 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                 Write(Url.Package(dependency.Id));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 98 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                              Write(dependency.Id);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                                    <td>");


            
            #line 99 "..\..\Views\Packages\DisplayPackage.cshtml"
                                   Write(dependency.VersionSpec);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                </tr>\r\n");


            
            #line 101 "..\..\Views\Packages\DisplayPackage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            </table>\r\n");


            
            #line 103 "..\..\Views\Packages\DisplayPackage.cshtml"
                        }
                        else {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"dependencies\">\r\n                         " +
"       <em>No Dependencies</em>\r\n                            </div>\r\n");


            
            #line 108 "..\..\Views\Packages\DisplayPackage.cshtml"
                        }                            

            
            #line default
            #line hidden
WriteLiteral(@"                        <h4 class=""details-header"">Version history</h4>
                        <table class=""packages"" cellpadding=""0"" cellspacing=""0"">
                            <thead>
                                <tr class=""header"">
                                    <th class=""version"">
                                        Version
                                    </th>
                                    <th class=""downloads"">
                                        Downloads
                                    </th>
                                    <th class=""lastUpdated"">
                                        Last updated
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
");


            
            #line 125 "..\..\Views\Packages\DisplayPackage.cshtml"
                                 foreach (var packageVersion in Model.PackageVersions) {

            
            #line default
            #line hidden

            
            #line 126 "..\..\Views\Packages\DisplayPackage.cshtml"
WriteLiteral("                                    <tr class=\"versionTableRow ");

            
            #line default
            #line hidden
            
            #line 126 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                if (packageVersion.LatestVersion) {
            
            #line default
            #line hidden
WriteLiteral("recommended ");


            
            #line 126 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                            }
            
            #line default
            #line hidden

            
            #line 126 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                               if (packageVersion.IsCurrent(Model)) {
            
            #line default
            #line hidden
WriteLiteral("current");


            
            #line 126 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                                                                         }
            
            #line default
            #line hidden

            
            #line 126 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                                                                          WriteLiteral(" \">\r\n                                        <td class=\"version\" ");

            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                             if (packageVersion.LatestVersion) {
            
            #line default
            #line hidden
WriteLiteral("title=\"Latest Version\"");


            
            #line 127 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");


            
            #line 128 "..\..\Views\Packages\DisplayPackage.cshtml"
                                             if (!packageVersion.IsCurrent(Model)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <a href=\"");


            
            #line 129 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                    Write(Url.Package(packageVersion));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 129 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                  Write(packageVersion.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 129 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                                                        Write(packageVersion.Version);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 130 "..\..\Views\Packages\DisplayPackage.cshtml"
                                            }
                                            else {

            
            #line default
            #line hidden
WriteLiteral("                                                <span>");


            
            #line 132 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                 Write(packageVersion.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 132 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                                       Write(packageVersion.Version);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 133 "..\..\Views\Packages\DisplayPackage.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </td>\r\n                                  " +
"      <td class=\"downloads\">");


            
            #line 135 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                         Write(packageVersion.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </td>\r\n                                " +
"        <td class=\"lastUpdated\">");


            
            #line 137 "..\..\Views\Packages\DisplayPackage.cshtml"
                                                           Write(packageVersion.LastUpdated.ToString("D"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </td>\r\n                                " +
"    </tr>\r\n");


            
            #line 140 "..\..\Views\Packages\DisplayPackage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tbody>\r\n                        </table>\r\n         " +
"           </div>\r\n                </section>\r\n            </div>\r\n        </div" +
">\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
