#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Packages
{
    using NuGetGallery;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Packages/ManagePackageOwners.cshtml")]
    public class ManagePackageOwners : System.Web.Mvc.WebViewPage<ManagePackageOwnersViewModel>
    {
        public ManagePackageOwners()
        {
        }
        public override void Execute()
        {



#line 2 "..\..\Views\Packages\ManagePackageOwners.cshtml"

            ViewBag.Tab = "Packages";



#line default
#line hidden
            WriteLiteral(@"<div id=""layout-main"" class=""group"">
    <div id=""layout-content"" class=""group"">
        <div id=""content"" class=""group"">
            <div class=""zone zone-content"">
                <section>
                    <header>
                        <h2>Manage Owners for Package """);



#line 11 "..\..\Views\Packages\ManagePackageOwners.cshtml"
            Write(Model.Title);


#line default
#line hidden
            WriteLiteral(@"""</h2>
                        <div class=""message message-Error validation-summary-errors"" data-bind=""text: message, visible: message""></div>
                    </header>
                    <div id=""form"">
                        <div>
                            <label>Current Owners</label>
                            <ul id=""package-owner-list"" data-bind=""foreach: owners"">
                                <li>
                                    <span data-bind=""text: name""></span>
                                    <a href=""#"" class=""delete"" data-bind=""visible: !current, click: remove"">Remove</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <form action=""");



#line 26 "..\..\Views\Packages\ManagePackageOwners.cshtml"
            Write(Url.Current());


#line default
#line hidden
            WriteLiteral(@""" id=""form"" method=""post"">
                            <div>
                                <label for=""newOwnerUserName"">Add New Owner</label>
                                <p>
                                    Enter an owner's username to add them as a package owner.
                                </p>
                                <aside style=""width: 357px !important;"">
                                    <p>
                                        <strong>NOTE:</strong> All package owners have full control over their packages,
                                        including the ability to remove other users as owners.</p>
                                </aside>
                                <input type=""text"" id=""newOwnerUserName"" data-bind=""value: newOwner().name"" class=""long"" />
                            </div>
                            <div class=""buttons"">   
                                <input type=""submit"" value=""Add"" data-bind=""click: addOwner"" />
                            </div>
                        </form>
                    </div>
                </section>
            </div>
    </div>
</div>
</div> 
<script src=""");



#line 49 "..\..\Views\Packages\ManagePackageOwners.cshtml"
            Write(Url.Content("~/Scripts/knockout-latest.js"));


#line default
#line hidden
            WriteLiteral("\" type=\"text/javascript\"></script>\r\n<script src=\"");



#line 50 "..\..\Views\Packages\ManagePackageOwners.cshtml"
            Write(Url.Content("~/json/JsonApi?json"));


#line default
#line hidden
            WriteLiteral(@""" type=""text/javascript""></script>
<script type=""text/javascript"">
    $(function() {
        //TODO Move this to its own script file when we set up QUnit tests
        var failHandler = function() {
            alert('An unexpected error occurred!');
        };

        var viewModel = {
            package: { id: '");



#line 59 "..\..\Views\Packages\ManagePackageOwners.cshtml"
            Write(Model.Id);


#line default
#line hidden
            WriteLiteral("\', version: \'");



#line 59 "..\..\Views\Packages\ManagePackageOwners.cshtml"
            Write(Model.Version);


#line default
#line hidden
            WriteLiteral("\' },\r\n            owners: ko.observableArray([]),\r\n            newOwner: ko.obser" +
            "vable(new Owner(null)),\r\n            message: ko.observable(\'\'),\r\n            ad" +
            "dOwner: function() {\r\n                var ownerInputModel = viewModel.newOwner()" +
            ".toJS();\r\n                ownerInputModel.id = viewModel.package.id;\r\n          " +
            "      \r\n                $mvc.JsonApi.AddPackageOwner(ownerInputModel)\r\n         " +
            "           .done(function(data) {\r\n                        if (data.success) {\r\n" +
            "                            viewModel.newOwner().name(data.name);\r\n             " +
            "               viewModel.owners.push(viewModel.newOwner());\r\n                   " +
            "         viewModel.newOwner(new Owner(null));\r\n                        }\r\n      " +
            "                  else {\r\n                            viewModel.message(data.mes" +
            "sage);\r\n                        }\r\n                    })\r\n                    ." +
            "fail(failHandler);\r\n            },\r\n\r\n            removeOwner: function(item) {\r" +
            "\n                var package = viewModel.package;\r\n                $mvc.JsonApi." +
            "RemovePackageOwner({ id: package.id, version: package.version, username: item.na" +
            "me() })\r\n                    .done(function(data) {\r\n                        if " +
            "(data.success) {\r\n                            viewModel.owners.remove(item);\r\n  " +
            "                      }\r\n                        else {\r\n                       " +
            "     viewModel.message(data.message);\r\n                        }\r\n              " +
            "      }).fail(failHandler);\r\n            }\r\n        };\r\n        ko.applyBindings" +
            "(viewModel);\r\n\r\n        // Load initial owners.\r\n        $mvc.JsonApi.GetPackage" +
            "Owners(viewModel.package)\r\n        .done(function(data) {\r\n            viewModel" +
            ".owners($.map(data, function(item) { return new Owner(item) }));\r\n        })\r\n  " +
            "      .fail(failHandler);\r\n\r\n        function Owner(item) {\r\n            var $th" +
            "is = this;\r\n\r\n            item = item || {};\r\n\r\n            this.name = ko.obser" +
            "vable(item.name);\r\n            this.current = item.current;\r\n            this.re" +
            "move = function() {\r\n                viewModel.removeOwner(this);\r\n            }" +
            ";\r\n            this.toJS = function() {\r\n                return { username: this" +
            ".name() };\r\n            };\r\n        }\r\n    });\r\n</script>");


        }
    }
}
#pragma warning restore 1591
