#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Packages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    
    #line 1 "..\..\Views\Packages\PublishPackage.cshtml"
    using NuGetGallery;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Packages/PublishPackage.cshtml")]
    public class PublishPackage : System.Web.Mvc.WebViewPage<SubmitPackageViewModel>
    {
        public PublishPackage()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Packages\PublishPackage.cshtml"
  
    ViewBag.Tab = "Upload";
    Layout = "~/Views/Shared/TwoColumnLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("SideColumn", () => {

WriteLiteral("\r\n    <img src=\"");


            
            #line 9 "..\..\Views\Packages\PublishPackage.cshtml"
         Write(Links.Content.Images.contribGraphic_png);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Contribution image\" />\r\n    <p>Submit your package for others to enjoy.</p" +
">\r\n");


});

WriteLiteral("    \r\n   \r\n<h1>Verify Details &amp; Submit</h1>\r\n");


            
            #line 14 "..\..\Views\Packages\PublishPackage.cshtml"
Write(ViewHelpers.UploadSequence(2));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<h2>Verify Details</h2>\r\n<p class=\"long note\">\r\n    These package details a" +
"re read from the package file and cannot be changed. \r\n    If you have a newer v" +
"ersion of your package that you’d like to submit in place \r\n    of this one, <a " +
"href=\"");


            
            #line 21 "..\..\Views\Packages\PublishPackage.cshtml"
                     Write(Url.UploadPackage());

            
            #line default
            #line hidden
WriteLiteral("\">click here to add a new \r\n    contribution</a>. Ensure that the new version has" +
" the same Package ID, but a \r\n    new Version number.\r\n</p>\r\n\r\n<ul id=\"packageDe" +
"tails\">\r\n    <li>\r\n        <h3>Package ID</h3>\r\n        <p>");


            
            #line 29 "..\..\Views\Packages\PublishPackage.cshtml"
      Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </li>\r\n    <li>\r\n        <h3>Version</h3>\r\n        <p>");


            
            #line 33 "..\..\Views\Packages\PublishPackage.cshtml"
      Write(Model.Version);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </li>\r\n");


            
            #line 35 "..\..\Views\Packages\PublishPackage.cshtml"
     if (!String.IsNullOrEmpty(Model.Title)) {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <h3>Title</h3>\r\n            <p>");


            
            #line 38 "..\..\Views\Packages\PublishPackage.cshtml"
          Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n        </li>\r\n");


            
            #line 40 "..\..\Views\Packages\PublishPackage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <li>\r\n        <h3>Description</h3>\r\n        <p>");


            
            #line 43 "..\..\Views\Packages\PublishPackage.cshtml"
      Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </li>\r\n    <li>\r\n        <h3>Authors</h3>\r\n        <p>");


            
            #line 47 "..\..\Views\Packages\PublishPackage.cshtml"
      Write(Model.Authors);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </li>\r\n");


            
            #line 49 "..\..\Views\Packages\PublishPackage.cshtml"
     if (!String.IsNullOrEmpty(Model.Tags)) {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <h3>Tags</h3>\r\n            <p>");


            
            #line 52 "..\..\Views\Packages\PublishPackage.cshtml"
          Write(Model.Tags);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n        </li>\r\n");


            
            #line 54 "..\..\Views\Packages\PublishPackage.cshtml"
    }

            
            #line default
            #line hidden

            
            #line 55 "..\..\Views\Packages\PublishPackage.cshtml"
     if (!String.IsNullOrEmpty(Model.LicenseUrl)) {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <h3>License URL</h3>\r\n            <p>\r\n");


            
            #line 59 "..\..\Views\Packages\PublishPackage.cshtml"
                 if (Model.RequiresLicenseAcceptance) {
            
            #line default
            #line hidden
WriteLiteral("Acceptance of license required: ");


            
            #line 59 "..\..\Views\Packages\PublishPackage.cshtml"
                                                                                                    }

            
            #line default
            #line hidden
WriteLiteral("                <a href=\"");


            
            #line 60 "..\..\Views\Packages\PublishPackage.cshtml"
                    Write(Model.LicenseUrl);

            
            #line default
            #line hidden
WriteLiteral("\" target=\"_blank\">");


            
            #line 60 "..\..\Views\Packages\PublishPackage.cshtml"
                                                       Write(Model.LicenseUrl);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                \r\n            </p>\r\n        </li>\r\n");


            
            #line 64 "..\..\Views\Packages\PublishPackage.cshtml"
    }

            
            #line default
            #line hidden

            
            #line 65 "..\..\Views\Packages\PublishPackage.cshtml"
     if (!String.IsNullOrEmpty(Model.ProjectUrl)) {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <h3>Project URL</h3>\r\n            <p><a href=\"");


            
            #line 68 "..\..\Views\Packages\PublishPackage.cshtml"
                   Write(Model.ProjectUrl);

            
            #line default
            #line hidden
WriteLiteral("\" target=\"_blank\">");


            
            #line 68 "..\..\Views\Packages\PublishPackage.cshtml"
                                                      Write(Model.ProjectUrl);

            
            #line default
            #line hidden
WriteLiteral("</a></p>\r\n        </li>\r\n");


            
            #line 70 "..\..\Views\Packages\PublishPackage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\n\r\n<h2>Submit Package</h2>\r\n");


            
            #line 75 "..\..\Views\Packages\PublishPackage.cshtml"
 using (Html.BeginForm()) {

            
            #line default
            #line hidden
WriteLiteral("<fieldset class=\"form\">\r\n    <legend>Submit Package</legend>\r\n    ");


            
            #line 78 "..\..\Views\Packages\PublishPackage.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"form-field\">\r\n        ");


            
            #line 80 "..\..\Views\Packages\PublishPackage.cshtml"
   Write(Html.EditorFor(package => package.Listed));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <label for=\"Listed\" class=\"checkbox\">\r\n            List this package in" +
" search results. \r\n        </label>\r\n    </div>\r\n    <input type=\"submit\" value=" +
"\"Submit\" title=\"Verify Details &amp; Submit\" />\r\n</fieldset>\r\n");


            
            #line 87 "..\..\Views\Packages\PublishPackage.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
