using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace NuGetGallery.Login
{
    public class LoginDiscontinuation
    {
        public bool IsPasswordDiscontinuedForAll { get; }
        public HashSet<string> DiscontinuedForEmailAddresses { get; set; }
        public HashSet<string> DiscontinuedForDomains { get; }
        public HashSet<string> ExceptionsForEmailAddresses { get; set; }
        public HashSet<string> ForceTransformationToOrganizationForEmailAddresses { get; }
        public HashSet<OrganizationTenantPair> EnabledOrganizationAadTenants { get; }
        
        public LoginDiscontinuation(
            IEnumerable<string> discontinuedForEmailAddresses,
            IEnumerable<string> discontinuedForDomains,
            IEnumerable<string> exceptionsForEmailAddresses,
            IEnumerable<string> forceTransformationToOrganizationForEmailAddresses,
            IEnumerable<OrganizationTenantPair> enabledOrganizationAadTenants,
            bool isPasswordDiscontinuedForAll)
        {
            DiscontinuedForEmailAddresses = new HashSet<string>(discontinuedForEmailAddresses, StringComparer.OrdinalIgnoreCase);
            DiscontinuedForDomains = new HashSet<string>(discontinuedForDomains, StringComparer.OrdinalIgnoreCase);
            ExceptionsForEmailAddresses = new HashSet<string>(exceptionsForEmailAddresses, StringComparer.OrdinalIgnoreCase);
            ForceTransformationToOrganizationForEmailAddresses = new HashSet<string>(forceTransformationToOrganizationForEmailAddresses, StringComparer.OrdinalIgnoreCase);
            EnabledOrganizationAadTenants = new HashSet<OrganizationTenantPair>(enabledOrganizationAadTenants);
            IsPasswordDiscontinuedForAll = isPasswordDiscontinuedForAll;
        }
    }
    public class OrganizationTenantPair
    {
        public string EmailDomain { get; }
        public string TenantId { get; }

        [JsonConstructor]
        public OrganizationTenantPair(string emailDomain, string tenantId)
        {
            EmailDomain = emailDomain ?? throw new ArgumentNullException(nameof(emailDomain));
            TenantId = tenantId ?? throw new ArgumentNullException(nameof(tenantId));
        }

        public override bool Equals(object obj)
        {
            return Equals(obj as OrganizationTenantPair);
        }

        public bool Equals(OrganizationTenantPair other)
        {
            return other != null &&
                string.Equals(EmailDomain, other.EmailDomain, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(TenantId, other.TenantId, StringComparison.OrdinalIgnoreCase);
        }

        /// <remarks>
        /// Autogenerated by "Quick Actions and Refactoring" -> "Generate Equals and GetHashCode".
        /// </remarks>
        public override int GetHashCode()
        {
            var hashCode = -1334890813;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(EmailDomain.ToLowerInvariant());
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(TenantId.ToLowerInvariant());
            return hashCode;
        }
    }
}
