<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
    <RootNamespace>NuGetGallery.CookieInteropTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NuGetGallery.Core\NuGetGallery.Core.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" />
    <PackageReference Include="Microsoft.Owin.Security.Cookies" />
    <PackageReference Include="Microsoft.Owin.Security.Interop" />
    <PackageReference Include="Microsoft.Owin.Testing" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Compile Remove="CoreCookieRunner.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <Compile Remove="LegacyCookieRunner.cs" />
  </ItemGroup>
</Project>
