// <auto-generated />
namespace NuGet.Services.Validation
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropCreateDbOptionOnSymbolServerRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropCreateDbOptionOnSymbolServerRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201808040003590_DropCreateDbOptionOnSymbolServerRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
