//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Jobs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Jobs.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the Totals from the query -- no records were returned..
        /// </summary>
        public static string CalculateStatsTotalsJob_NoData {
            get {
                return ResourceManager.GetString("CalculateStatsTotalsJob_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source database &apos;{0}&apos; was not found..
        /// </summary>
        public static string CreateOnlineDatabaseBackupJob_MissingSourceDatabase {
            get {
                return ResourceManager.GetString("CreateOnlineDatabaseBackupJob_MissingSourceDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown warehouse report: &apos;{0}&apos;.
        /// </summary>
        public static string CreateWarehouseReportsJob_UnknownReport {
            get {
                return ResourceManager.GetString("CreateWarehouseReportsJob_UnknownReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event Source &apos;{0}&apos; does not have a public static field &quot;Log&quot; containing an instance of it. Event Sources must implement this pattern for all jobs..
        /// </summary>
        public static string EventSourceInstanceManager_EventSourceDoesNotHaveLogField {
            get {
                return ResourceManager.GetString("EventSourceInstanceManager_EventSourceDoesNotHaveLogField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package has no manifest: {0} {1} (URL: {2}).
        /// </summary>
        public static string HandlePackageEditsJob_MissingManifest {
            get {
                return ResourceManager.GetString("HandlePackageEditsJob_MissingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package has multiple manifests: {0} {1} (URL: {2}).
        /// </summary>
        public static string HandlePackageEditsJob_MultipleManifests {
            get {
                return ResourceManager.GetString("HandlePackageEditsJob_MultipleManifests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation result cannot be incomplete!.
        /// </summary>
        public static string InvocationResult_CannotBeIncomplete {
            get {
                return ResourceManager.GetString("InvocationResult_CannotBeIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation result in the &apos;{0}&apos; state must include a Continuation.
        /// </summary>
        public static string InvocationResult_ResultMustHaveContinuation {
            get {
                return ResourceManager.GetString("InvocationResult_ResultMustHaveContinuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation result in the &apos;{0}&apos; state must include an Exception.
        /// </summary>
        public static string InvocationResult_ResultMustHaveException {
            get {
                return ResourceManager.GetString("InvocationResult_ResultMustHaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation result in the &apos;{0}&apos; state must not include a Continuation.
        /// </summary>
        public static string InvocationResult_ResultMustNotHaveContinuation {
            get {
                return ResourceManager.GetString("InvocationResult_ResultMustNotHaveContinuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation result in the &apos;{0}&apos; state must not include an Exception.
        /// </summary>
        public static string InvocationResult_ResultMustNotHaveException {
            get {
                return ResourceManager.GetString("InvocationResult_ResultMustNotHaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation result in the &apos;{0}&apos; state must not include an RescheduleIn time.
        /// </summary>
        public static string InvocationResult_ResultMustNotHaveRescheduleIn {
            get {
                return ResourceManager.GetString("InvocationResult_ResultMustNotHaveRescheduleIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Invocation ID in message: &apos;{0}&apos;.
        /// </summary>
        public static string InvocationsQueue_InvalidInvocationId {
            get {
                return ResourceManager.GetString("InvocationsQueue_InvalidInvocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct job from this job description, it was loaded from a table.
        /// </summary>
        public static string JobDescription_CannotBeConstructed {
            get {
                return ResourceManager.GetString("JobDescription_CannotBeConstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to invoke continuation of non-async job: {0}..
        /// </summary>
        public static string JobDispatcher_AsyncContinuationOfNonAsyncJob {
            get {
                return ResourceManager.GetString("JobDispatcher_AsyncContinuationOfNonAsyncJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalServiceHost failed to start..
        /// </summary>
        public static string LocalWorker_FailedToStart {
            get {
                return ResourceManager.GetString("LocalWorker_FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown job: {0}.
        /// </summary>
        public static string UnknownJobException_Message {
            get {
                return ResourceManager.GetString("UnknownJobException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON data does not match schema..
        /// </summary>
        public static string UpdateLicenseReportsJob_JsonDoesNotMatchSchema {
            get {
                return ResourceManager.GetString("UpdateLicenseReportsJob_JsonDoesNotMatchSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided Framework is not supported..
        /// </summary>
        public static string V2Search_InvalidFrameworkParameter {
            get {
                return ResourceManager.GetString("V2Search_InvalidFrameworkParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided TFM is not supported..
        /// </summary>
        public static string V2Search_InvalidTFMParameter {
            get {
                return ResourceManager.GetString("V2Search_InvalidTFMParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of Destination or OutputDirectory must be specified or available from the environment.
        /// </summary>
        public static string WarehouseJob_NoDestinationAvailable {
            get {
                return ResourceManager.GetString("WarehouseJob_NoDestinationAvailable", resourceCulture);
            }
        }
    }
}
