#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Pages
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NuGetGallery;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pages/Home.cshtml")]
    public class Home : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Home()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Pages\Home.cshtml"
  
    ViewBag.Tab = "Home";


            
            #line default
            #line hidden
WriteLiteral("<div id=\"layout-main\" class=\"group\">\n    <div id=\"layout-content\" class=\"group\">\n" +
"        <div id=\"content\" class=\"group\">\n            <div class=\"zone zone-conte" +
"nt\">\n                <article class=\"content-item page\">\n                    <di" +
"v class=\"MIX-hero\">\n                        <div class=\"MIX-hero-text\">\n        " +
"                    <h2 style=\"font-size: 25px; font-weight: normal; text-shadow" +
": rgba(0,0,0,.1) 0px 0px 1px;\">Jump Start Your Projects with NuGet</h2>\n        " +
"                    <p style=\"font-size: 18px; line-height: 30px;\">NuGet is a Vi" +
"sual Studio extension that makes it easy to install and update open source libra" +
"ries and tools in Visual Studio.</p>\n                            <p style=\"font-" +
"size: 16px;\"><em>So <a href=\"http://visualstudiogallery.msdn.microsoft.com/en-us" +
"/27077b70-9dad-4c64-adcf-c7cf6bc9970c/file/37502/5/NuGet.Tools.signed.vsix\">inst" +
"all NuGet</a> and get a jump on your next project!</em></p>\n                    " +
"        <p><a class=\"install\" style=\"margin: 36px 0 0 0;\" href=\"http://visualstu" +
"diogallery.msdn.microsoft.com/en-us/27077b70-9dad-4c64-adcf-c7cf6bc9970c/file/37" +
"502/5/NuGet.Tools.signed.vsix\">Install NuGet</a></p>\n                        </d" +
"iv>\n                    </div>\n                </article>\n            </div>\n   " +
"     </div>\n    </div>\n    <div id=\"layout-after-main\" class=\"group\">\n        <d" +
"iv class=\"zone zone-after-main\">\n            <article class=\"widget-html-widget " +
"widget\">\n                <div class=\"MIX-secondary group\">\n                    <" +
"div style=\"float: left; width: 470px; margin: 0 0 24px 0;\">\n                    " +
"    <h3 style=\"font-size: 18px; font-weight: normal;\">About</h3>\n               " +
"         <p style=\"font-size: 14px; line-height: 26px;\">When you use NuGet to in" +
"stall a package, it copies the library files to your solution and automatically " +
"updates your project (add references, change config files, etc). If you remove a" +
" package, NuGet reverses whatever changes it made so that no clutter is left.</p" +
">\n                    </div>\n                    <div style=\"float: right; width" +
": 470px; margin: 0 0 24px 0;\">\n                        <h3 style=\"font-size: 18p" +
"x; font-weight: bold;\">NuGet 1.4 released!</h3>\n                        <p style" +
"=\"font-size: 14px; line-height: 26px;\">Take 5 minutes and UPGRADE NOW using the " +
"Visual Studio Extension Manager. Why? Because there&rsquo;s a pile of new featur" +
"es and it will make your life easier!<br /> All these details and <a href=\"http:" +
"//docs.nuget.org/docs/release-notes/nuget-1.4\">more here...</a></p>\n            " +
"        </div>\n                    <div class=\"MIX-notice\">\n                    " +
"    <h3 style=\"font-size: 18px; font-weight: normal;\">Important Notice</h3>\n    " +
"                    <p style=\"font-size: 14px; line-height: 26px;\">You can devel" +
"op your own package and share it via the NuGet Gallery. Read the documentation f" +
"or more details on <a title=\"Creating and submitting a package\" href=\"http://doc" +
"s.nuget.org/docs/creating-packages/creating-and-publishing-a-package\">how to cre" +
"ate and publish a package</a>. If you don&rsquo;t plan on submitting a package, " +
"there&rsquo;s no need to register.</p>\n                    </div>\n              " +
"  </div>\n            </article>\n        </div>\n    </div>\n</div>\n");


        }
    }
}
#pragma warning restore 1591
