#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Pages
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pages/Terms.cshtml")]
    public class Terms : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Terms()
        {
        }
        public override void Execute()
        {
            WriteLiteral("<article class=\"policies\">\r\n    <h2>TERMS &amp; CONDITIONS</h2>\r\n    <h3>Terms of" +
            " Use</h3>\r\n    <p class=\"content\">\r\n        <strong>Legal Notices.</strong> The " +
            "Outercurve Foundation (Outercurve) Web site\r\n        nuget.org (the \"Web site\") " +
            "is provided by Outercurve as a public service to our\r\n        users. Please care" +
            "fully review the following basic rules that govern your use of\r\n        the Web " +
            "site. Please note that your use of the Web site constitutes your unconditional\r\n" +
            "        agreement to follow and be bound by these Terms and Conditions of Use. I" +
            "f you (\"User\")\r\n        do not agree to them, do not use the Web site, provide a" +
            "ny materials to the site\r\n        or download any materials from it. Outercurve " +
            "reserves the right to update or modify\r\n        these Terms and Conditions at an" +
            "y time without prior notice to User. Your use of\r\n        the site following any" +
            " such change constitutes your unconditional agreement to follow\r\n        and be " +
            "bound by these Terms and Conditions as changed. For this reason, we encourage\r\n " +
            "       you to review these Terms and Conditions of Use whenever you use this Web" +
            " site.\r\n        These Terms and Conditions of Use apply to the use of the Outerc" +
            "urve site and do\r\n        not extend to any linked third party sites. These Term" +
            "s and Conditions and our <a\r\n            title=\"NuGet Privacy Policy\" href=\"http" +
            "://nuget.org/policies/privacy\">Privacy Policy</a>,\r\n        which are hereby inc" +
            "orporated by reference, contain the entire agreement (the \"Agreement\")\r\n        " +
            "between Outercurve and User with respect to this site. Any rights not expressly\r" +
            "\n        granted herein are reserved.\r\n    </p>\r\n    <p class=\"content\">\r\n      " +
            "  <strong>Permitted and Prohibited Uses.</strong> User may use the Outercurve We" +
            "b\r\n        site for the sole purpose of allowing Outercurve professionals to sha" +
            "re and exchange\r\n        their ideas. User may not use the Outercurve Web site t" +
            "o violate any applicable\r\n        local, state, national, or international law, " +
            "including without limitation any applicable\r\n        laws relating to antitrust " +
            "or other illegal trade or business practices, federal\r\n        and state securit" +
            "ies laws, regulations promulgated by the U.S. Securities and Exchange\r\n        C" +
            "ommission, any rules of any national or other securities exchange, and any U.S.\r" +
            "\n        laws, rules, and regulations governing the export and re-export of comm" +
            "odities or\r\n        technical data. User may not upload or transmit any material" +
            " that infringes or misappropriates\r\n        any person\'s copyright, patent, trad" +
            "emark, or trade secret, or disclose via the\r\n        Outercurve Web site any inf" +
            "ormation the disclosure of which would constitute a violation\r\n        of a conf" +
            "identiality obligation on User\'s part. User may not upload any viruses,\r\n       " +
            " worms, Trojan horses, or other forms of harmful computer code, nor subject Oute" +
            "rcurve&rsquo;s\r\n        network or servers to unreasonable traffic loads, or oth" +
            "erwise engage in conduct\r\n        deemed disruptive to the ordinary operation of" +
            " Outercurve&rsquo;s Web site. User\r\n        is strictly prohibited from communic" +
            "ating on or through this site any unlawful,\r\n        harmful, offensive, threate" +
            "ning, abusive, libelous, harassing, defamatory, vulgar,\r\n        obscene, profan" +
            "e, hateful, fraudulent, sexually explicit, racially, ethnically,\r\n        or oth" +
            "erwise objectionable material of any sort, including, but not limited to,\r\n     " +
            "   any material that encourages conduct that would constitute a criminal offense" +
            ", give\r\n        rise to civil liability, or otherwise violate any applicable loc" +
            "al, state, national,\r\n        or international law.\r\n    </p>\r\n    <p class=\"con" +
            "tent\">\r\n        <strong>User Submissions.</strong> Outercurve does not want to r" +
            "eceive confidential\r\n        or proprietary information from User through this s" +
            "ite. Any material, information,\r\n        or other communication User transmits o" +
            "r posts (\"Communications\") to Outercurve&rsquo;s\r\n        Web site will be consi" +
            "dered non-confidential and non-proprietary and Outercurve\r\n        will be under" +
            " no obligation of any kind with respect to such information. Outercurve\r\n       " +
            " will be free to reproduce, make derivative works from, use, disclose, and distr" +
            "ibute\r\n        the Communications to others without limitation. At our sole elec" +
            "tion, Outercurve\r\n        may provide authorship attribution by listing User\'s n" +
            "ame.\r\n    </p>\r\n    <p class=\"content\">\r\n        <strong>User Discussion Forums." +
            "</strong> Outercurve may, but is not obligated to,\r\n        monitor or review an" +
            "y areas on Outercurve&rsquo;s Web site where users transmit\r\n        or post com" +
            "munications or communicate solely with each other, including but not\r\n        li" +
            "mited to chat rooms, bulletin boards or other user forums, and the content of\r\n " +
            "       any such communications. Outercurve, however, will have no liability rela" +
            "ted to\r\n        the content of any such communications, whether or not arising u" +
            "nder the laws of\r\n        copyright, libel, privacy, obscenity, or otherwise. Ou" +
            "tercurve may edit or remove\r\n        content on the Outercurve Web site at its d" +
            "iscretion at any time.\r\n    </p>\r\n    <p class=\"content\">\r\n        <strong>Use o" +
            "f Personally Identifiable Information.</strong> Information submitted\r\n        t" +
            "o the Outercurve Web site is governed according to Outercurve&rsquo;s then-curre" +
            "nt\r\n        <a title=\"NuGet Privacy Policy\" href=\"http://nuget.org/policies/priv" +
            "acy\">Privacy Policy</a>.\r\n    </p>\r\n    <p class=\"content\">\r\n        User agrees" +
            " to provide true, accurate, current, and complete information when registering\r\n" +
            "        with our Web site. It is User\'s responsibility to maintain and promptly " +
            "update this\r\n        account information to keep it true, accurate, current, and" +
            " complete. If User provides\r\n        any information that is fraudulent, untrue," +
            " inaccurate, incomplete, or not current,\r\n        or we have reasonable grounds " +
            "to suspect that such information is fraudulent, untrue,\r\n        inaccurate, inc" +
            "omplete, or not current, we reserve the right to suspend or terminate\r\n        y" +
            "our account without notice and to refuse any and all current and future use of\r\n" +
            "        this site.\r\n    </p>\r\n    <p class=\"content\">\r\n        Although sections" +
            " of the site may be viewed simply by visiting the site, in order\r\n        to acc" +
            "ess some Content and/or additional features offered at the site, you may need\r\n " +
            "       to sign on as a guest or register as a member. If you create an account o" +
            "n the site,\r\n        you may be asked to supply your name, address, a User ID an" +
            "d password. You are responsible\r\n        for maintaining the confidentiality of " +
            "the password and account and are fully responsible\r\n        for all activities t" +
            "hat occur in connection with your password or account. You agree\r\n        to imm" +
            "ediately notify us of any unauthorized use of either your password or account\r\n " +
            "       or any other breach of security. You further agree that you will not perm" +
            "it others,\r\n        including those whose accounts have been terminated, to acce" +
            "ss this site using your\r\n        account or User ID. You grant Outercurve, its a" +
            "ffiliated companies, and all other\r\n        persons or entities involved in the " +
            "operation of the Site the right to transmit,\r\n        monitor, retrieve, store, " +
            "and use your information in connection with the operation\r\n        of the Site a" +
            "nd in the provision of services to you. Outercurve cannot and does\r\n        not " +
            "assume any responsibility or liability for any information you submit, or your\r\n" +
            "        or third parties\' use or misuse of information transmitted or received u" +
            "sing Outercurve&rsquo;s\r\n        site. To learn more about how we protect the pr" +
            "ivacy of the personal information\r\n        in your account, please visit our <a " +
            "title=\"NuGet Privacy Policy\" href=\"http://nuget.org/policies/privacy\">\r\n        " +
            "    Privacy Policy</a>.\r\n    </p>\r\n    <p class=\"content\">\r\n        <strong>Inde" +
            "mnification.</strong> User agrees to defend, indemnify and hold harmless\r\n      " +
            "  Outercurve, its employees, directors, officers, affiliated companies, agents, " +
            "vendors\r\n        or suppliers from and against any and all claims, damages, cost" +
            "s and expenses, including\r\n        reasonable attorneys\' fees, arising from or r" +
            "elated to your use or misuse of the\r\n        site, including, without limitation" +
            ", User\'s violation of these Terms and Conditions,\r\n        the infringement by U" +
            "ser, or any other subscriber or user of your account, of any\r\n        intellectu" +
            "al property right or other right of any person or entity.</p>\r\n    <p class=\"con" +
            "tent\">\r\n        <strong>Termination.</strong> These Terms and Conditions of Use " +
            "are effective until\r\n        terminated by either party. If User no longer agree" +
            "s to be bound by these Terms\r\n        and Conditions, User must cease use of thi" +
            "s Web site. If User is dissatisfied with\r\n        this Web site, its content, or" +
            " any of these terms, conditions, and policies, User\'s\r\n        sole legal remedy" +
            " is to discontinue using this Web site. Outercurve reserves the\r\n        right t" +
            "o terminate or suspend your access to and use of this site, or parts of this\r\n  " +
            "      site, without notice, if we believe, in our sole discretion, that such use" +
            " is (i)\r\n        in violation of any applicable law; (ii) is harmful to our inte" +
            "rests or the interests,\r\n        including intellectual property or other rights" +
            ", of another person or entity; or\r\n        (iii) where Outercurve has reason to " +
            "believe that User is in violation of these\r\n        Terms and Conditions of Use." +
            "</p>\r\n    <p class=\"content\">\r\n        <strong>WARRANTY DISCLAIMER.</strong> OUT" +
            "ERCURVE WEB SITE AND ASSOCIATED MATERIALS\r\n        ARE PROVIDED ON AN \"AS IS\" AN" +
            "D \"AS AVAILABLE\" BASIS. TO THE FULL EXTENT PERMISSIBLE\r\n        BY APPLICABLE LA" +
            "W, OUTERCURVE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING,\r\n        " +
            "BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PART" +
            "ICULAR\r\n        PURPOSE, OR NON-INFRINGEMENT OF INTELLECTUAL PROPERTY. OUTERCURV" +
            "E MAKES NO REPRESENTATIONS\r\n        OR WARRANTY THAT THE SITE WILL MEET YOUR REQ" +
            "UIREMENTS, OR THAT YOUR USE OF THE SITE\r\n        WILL BE UNINTERRUPTED, TIMELY, " +
            "SECURE, OR ERROR FREE; NOR DOES OUTERCURVE MAKE ANY\r\n        REPRESENTATION OR W" +
            "ARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF\r\n        THE SITE" +
            ". OUTERCURVE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS\r\n      " +
            "  OR IMPLIED, AS TO THE OPERATION OF THE SITE OR THE INFORMATION, CONTENT, MATER" +
            "IALS,\r\n        OR PRODUCTS INCLUDED ON THIS SITE.</p>\r\n    <p class=\"content\">\r\n" +
            "        IN NO EVENT SHALL OUTERCURVE OR ANY OF ITS AFFILIATED COMPANIES, EMPLOYE" +
            "ES, DIRECTORS,\r\n        OFFICERS, AGENTS, VENDORS OR SUPPLIERS BE LIABLE FOR ANY" +
            " DAMAGES WHATSOEVER (INCLUDING,\r\n        WITHOUT LIMITATION, DAMAGES FOR LOSS OF" +
            " PROFITS, BUSINESS INTERRUPTION, LOSS OF\r\n        INFORMATION) ARISING OUT OF TH" +
            "E USE, MISUSE OF OR INABILITY TO USE THE SITE, EVEN\r\n        IF OUTERCURVE HAS B" +
            "EEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS DISCLAIMER\r\n        CONSTIT" +
            "UTES AN ESSENTIAL PART OF THIS AGREEMENT. BECAUSE SOME JURISDICTIONS PROHIBIT\r\n " +
            "       THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL " +
            "DAMAGES,\r\n        THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>\r\n    <p class=\"" +
            "content\">\r\n        YOU UNDERSTAND AND AGREE THAT ANY CONTENT DOWNLOADED OR OTHER" +
            "WISE OBTAINED THROUGH\r\n        THE USE OF THE SITE IS AT YOUR OWN DISCRETION AND" +
            " RISK AND THAT YOU WILL BE SOLELY\r\n        RESPONSIBLE FOR ANY DAMAGE TO YOUR CO" +
            "MPUTER SYSTEM OR LOSS OF DATA OR BUSINESS INTERRUPTION\r\n        THAT RESULTS FRO" +
            "M THE DOWNLOAD OF CONTENT. OUTERCURVE SHALL NOT BE RESPONSIBLE FOR\r\n        ANY " +
            "LOSS OR DAMAGE CAUSED, OR ALLEGED TO HAVE BEEN CAUSED, DIRECTLY OR INDIRECTLY,\r\n" +
            "        BY THE INFORMATION OR IDEAS CONTAINED, SUGGESTED OR REFERENCED IN OR APP" +
            "EARING ON\r\n        THE SITE. YOUR PARTICIPATION IN THE SITE IS SOLELY AT YOUR OW" +
            "N RISK. NO ADVICE OR\r\n        INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY " +
            "YOU FROM OUTERCURVE OR THROUGH\r\n        OUTERCURVE, ITS EMPLOYEES, OR THIRD PART" +
            "IES SHALL CREATE ANY WARRANTY NOT EXPRESSLY\r\n        MADE HEREIN. YOU ACKNOWLEDG" +
            "E, BY YOUR USE OF THE OUTERCURVE WEB SITE, THAT YOUR\r\n        USE OF THE SITE IS" +
            " AT YOUR SOLE RISK.</p>\r\n    <p class=\"content\">\r\n        <strong>Liability Limi" +
            "tation.</strong> UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL\r\n        OR EQUITABLE" +
            " THEORY, WHETHER IN TORT, CONTRACT, NEGLIGENCE, STRICT LIABILITY OR\r\n        OTH" +
            "ERWISE, SHALL OUTERCURVE OR ANY OF ITS AFFILIATED COMPANIES, EMPLOYEES, DIRECTOR" +
            "S,\r\n        OFFICERS, AGENTS, VENDORS OR SUPPLIERS BE LIABLE TO USER OR TO ANY O" +
            "THER PERSON\r\n        FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL LOSS" +
            "ES OR DAMAGES OF ANY\r\n        NATURE ARISING OUT OF OR IN CONNECTION WITH THE US" +
            "E OF OR INABILITY TO USE THE OUTERCURVE\r\n        WEB SITE OR FOR ANY BREACH OF S" +
            "ECURITY ASSOCIATED WITH THE TRANSMISSION OF SENSITIVE\r\n        INFORMATION THROU" +
            "GH THE OUTERCURVE WEB SITE OR FOR ANY INFORMATION OBTAINED THROUGH\r\n        THE " +
            "OUTERCURVE SITE, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS\r\n" +
            "        OF GOODWILL, LOSS OR CORRUPTION OF DATA, WORK STOPPAGE, ACCURACY OF RESU" +
            "LTS, OR\r\n        COMPUTER FAILURE OR MALFUNCTION, EVEN IF AN AUTHORIZED REPRESEN" +
            "TATIVE OF OUTERCURVE\r\n        HAS BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE PO" +
            "SSIBILITY OF SUCH DAMAGES.</p>\r\n    <p class=\"content\">\r\n        OUTERCURVE\'S TO" +
            "TAL CUMULATIVE LIABILITY FOR ANY AND ALL CLAIMS IN CONNECTION WITH\r\n        THE " +
            "OUTERCURVE\'S WEB SITE WILL NOT EXCEED TWENTY FIVE THOUSAND U.S. DOLLARS ($25,000" +
            ".00).\r\n        USER AGREES AND ACKNOWLEDGES THAT THE FOREGOING LIMITATIONS ON LI" +
            "ABILITY ARE AN\r\n        ESSENTIAL BASIS OF THE BARGAIN AND THAT OUTERCURVE WOULD" +
            " NOT PROVIDE THE OUTERCURVE&rsquo;S\r\n        WEB SITE ABSENT SUCH LIMITATION.</p" +
            ">\r\n    <p class=\"content\">\r\n        <strong>General.</strong> Outercurve is base" +
            "d in the United States. Outercurve makes\r\n        no claims that the Content on " +
            "the site is appropriate or may be downloaded outside\r\n        of the United Stat" +
            "es. Access to the Content may not be legal by certain persons\r\n        or in cer" +
            "tain countries. If you access the site from outside the United States,\r\n        " +
            "you do so at your own risk and are responsible for compliance with the laws of y" +
            "our\r\n        jurisdiction. These Terms are governed in all respects by the laws " +
            "of the State\r\n        of Delaware, excluding Delaware\'s conflicts of laws provis" +
            "ions. The provisions of\r\n        the UN Convention on Contracts for the Internat" +
            "ional Sale of Goods will not apply\r\n        to these Terms. A party may give not" +
            "ice to the other party only in writing at that\r\n        party\'s principal place " +
            "of business, attention of that party\'s principal legal officer,\r\n        or at s" +
            "uch other address or by such other method as the party shall specify in writing." +
            "\r\n        Notice shall be deemed given upon personal delivery or facsimile, or, " +
            "if sent by\r\n        certified mail with postage prepaid, 5 business days after t" +
            "he date of mailing,\r\n        or, if sent by international overnight courier with" +
            " postage prepaid, 7 business\r\n        days after the date of mailing. If any pro" +
            "vision herein is held to be unenforceable,\r\n        the remaining provisions wil" +
            "l continue in full force without being affected in any\r\n        way. Further, th" +
            "e parties agree to replace such unenforceable provision with an\r\n        enforce" +
            "able provision that most closely approximates the intent and economic effect\r\n  " +
            "      of the unenforceable provision. Section headings are for reference purpose" +
            "s only\r\n        and do not define, limit, construe or describe the scope or exte" +
            "nt of such section.\r\n        The failure of Outercurve to act with respect to a " +
            "breach of this Agreement by User\r\n        or others does not constitute a waiver" +
            " and shall not limit Outercurve&rsquo;s rights\r\n        with respect to such bre" +
            "ach or any subsequent breaches. Any action or proceeding\r\n        arising out of" +
            " or related to this Agreement or User\'s use of this site must be brought\r\n      " +
            "  in the state or federal courts of the State of California, and User consents t" +
            "o\r\n        the exclusive personal jurisdiction and venue of such courts. Any cau" +
            "se of action\r\n        you may have with respect to your use of this site must be" +
            " commenced within one\r\n        (1) year after the claim or cause of action arise" +
            "s. These Terms set forth the entire\r\n        understanding and agreement of the " +
            "parties, and supersedes any and all oral or written\r\n        agreements or under" +
            "standings between the parties, as to their subject matter. The\r\n        waiver o" +
            "f a breach of any provision of this Agreement shall not be construed as\r\n       " +
            " a waiver of any other or subsequent breach.</p>\r\n    <p class=\"content\">\r\n     " +
            "   <strong>Links to Other Materials.</strong> This Site may contain links to sit" +
            "es\r\n        owned or operated by independent third parties. These links are prov" +
            "ided for your\r\n        convenience and reference only. We do not control such si" +
            "tes and, therefore, we\r\n        are not responsible for any content posted on th" +
            "ese sites. The fact that Outercurve\r\n        offers such links should not be con" +
            "strued in any way as an endorsement, authorization,\r\n        or sponsorship of t" +
            "hat site, its content or the companies or products referenced\r\n        therein, " +
            "and Outercurve reserves the right to note its lack of affiliation, sponsorship,\r" +
            "\n        or endorsement on this site. If you decide to access any of the third p" +
            "arty sites\r\n        linked to this Site, you do this entirely at your own risk. " +
            "Because some sites employ\r\n        automated search results or otherwise link yo" +
            "u to sites containing information that\r\n        may be deemed inappropriate or o" +
            "ffensive, Outercurve cannot be held responsible\r\n        for the accuracy, copyr" +
            "ight compliance, legality, or decency of material contained\r\n        in third pa" +
            "rty sites, and you hereby irrevocably waive any claim against us with\r\n        r" +
            "espect to such sites.\r\n    </p>\r\n    <p class=\"content\">\r\n        <strong>Notifi" +
            "cation Of Possible Copyright Infringement.</strong> In the event you\r\n        be" +
            "lieve that material or content published on the site may infringe on your copyri" +
            "ght\r\n        or that of another, please provide detailed written notice of such " +
            "possible infringement\r\n        to <a title=\"Email Paula Hunter\" href=\"mailto://p" +
            "hunter@outercurve.org\">Paula Hunter,\r\n            Outercurve Foundation</a>, 781" +
            "-876-6227 (office), 781-224-1239 (fax).\r\n    </p>\r\n</article>\r\n");


        }
    }
}
#pragma warning restore 1591
