PREFIX nuget: <http://nuget.org/schema#>

CONSTRUCT
{
    @resource a nuget:Catalog ;
	          nuget:contains ?catalogPage .
}
WHERE
{
    @resource a nuget:Catalog ;
              nuget:contains ?catalogPage .
}
