PREFIX nuget: <http://nuget.org/schema#>

CONSTRUCT
{
    @resource a nuget:Package ;
              nuget:id ?id ;
              nuget:version ?version ;
              nuget:registration ?registration ;
			  nuget:authors ?authors ;
	          nuget:description ?description ;
			  nuget:licenseUrl ?licenseUrl ;
			  nuget:projectUrl ?projectUrl ;
			  nuget:iconUrl ?iconUrl ;
			  nuget:requireLicenseAcceptance ?requireLicenseAcceptance ;
			  nuget:releaseNotes ?releaseNotes ;
			  nuget:tag ?tag ;
			  nuget:published ?published ;
		      nuget:dependencies ?dependencies .

	?registration nuget:owner ?owner .

    ?dependencies nuget:group ?dependency_group .

    ?dependency_group nuget:dependency ?dependency ;
                      nuget:targetFramework ?dependency_group_targetFramework ;
					  nuget:name ?dependency_group_name ;
					  nuget:property ?dependency_group_property .

    ?dependency_group_property nuget:name ?dependency_group_property_name ;
                               nuget:value ?dependency_group_property_value .

	?dependency nuget:id ?dependency_id ;
				nuget:registration ?dependency_registration ;
				nuget:range ?dependency_version ;
				nuget:property ?dependency_property .

	?dependency_property nuget:name ?dependency_property_name ;
					     nuget:value ?dependency_property_value .
}
WHERE
{
    @resource nuget:id ?id ;
	          nuget:version ?version ;
	          nuget:registration ?registration .

	OPTIONAL { @resource nuget:authors ?authors . }
	OPTIONAL { @resource nuget:description ?description . }
	OPTIONAL { @resource nuget:licenseUrl ?licenseUrl . }
	OPTIONAL { @resource nuget:projectUrl ?projectUrl . }
	OPTIONAL { @resource nuget:iconUrl ?iconUrl . }
	OPTIONAL { @resource nuget:requireLicenseAcceptance ?requireLicenseAcceptance . }
	OPTIONAL { @resource nuget:releaseNotes ?releaseNotes . }
	OPTIONAL { @resource nuget:tag ?tag . }
	OPTIONAL { @resource nuget:published ?published . }

	?registration nuget:owner ?owner .

	OPTIONAL
	{
        @resource nuget:dependencies ?dependencies .
		?dependencies nuget:group ?dependency_group .

		?dependency_group nuget:dependency ?dependency .
		OPTIONAL { ?dependency_group nuget:targetFramework ?dependency_group_targetFramework . }
		OPTIONAL { ?dependency_group nuget:name ?dependency_group_name . }
		OPTIONAL 
		{ 
			?dependency_group nuget:property ?dependency_group_property .
			?dependency_group_property nuget:name ?dependency_group_property_name ;
								       nuget:value ?dependency_group_property_value .
		}
		
		?dependency nuget:id ?dependency_id ;
					nuget:registration ?dependency_registration .
		OPTIONAL { ?dependency nuget:range ?dependency_version . }
		OPTIONAL 
		{ 
			?dependency nuget:property ?dependency_property .
			?dependency_property nuget:name ?dependency_property_name ;
								 nuget:value ?dependency_property_value .
		}
	}
}
