PREFIX nuget: <http://nuget.org/schema#>

CONSTRUCT
{
    @resource a nuget:PackageRegistration ;
              nuget:id ?id ;
              nuget:owner ?owner ;
              nuget:package ?package .

	?package nuget:id ?packageId ;
			 nuget:version ?packageVersion ;
			 nuget:published ?published ;
             nuget:dependencies ?dependencies .

    ?dependencies nuget:group ?dependency_group .

    ?dependency_group nuget:dependency ?dependency ;
                      nuget:targetFramework ?targetFramework .

	?dependency nuget:id ?dependency_id ;
				nuget:registration ?dependency_registration ;
				nuget:range ?dependency_version .
}
WHERE
{
    @resource a nuget:PackageRegistration ;
                  nuget:id ?id ;
                  nuget:owner ?owner .

    ?package a nuget:Package ;
             nuget:registration @resource .

	?package nuget:id ?packageId ;
			 nuget:version ?packageVersion ;
			 nuget:published ?published .

	OPTIONAL
	{
        ?package nuget:dependencies ?dependencies .
		?dependencies nuget:group ?dependency_group .

		?dependency_group nuget:dependency ?dependency .
		OPTIONAL { ?dependency_group nuget:targetFramework ?targetFramework . }
		
		?dependency nuget:id ?dependency_id ;
					nuget:registration ?dependency_registration .

		OPTIONAL { ?dependency nuget:range ?dependency_version . }
	}
}
