blank_issues_enabled: true
contact_links:
  - name: NuGet Client Issue Tracker
    url: https://github.com/NuGet/Home/issues/new/choose
    about: Please file issues about the NuGet Client here.
  - name: Report Security Issue
    url: https://msrc.microsoft.com/
    about: Is your issue related to security? Please submit it securely through MSRC.
