// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace NuGetGallery.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class AddRegistrationLastEditedToPackageRegistrations : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.PackageRegistrations", "RegistrationLastEdited", c => c.DateTime());
            CreateIndex("dbo.PackageRegistrations", "RegistrationLastEdited", name: "IX_PackageRegistrations_RegistrationLastEdited");

            // If the "RegistrationLastEdited" field of a package registration was edited, update it to the current timestamp.
            // This guarantees that all "RegistrationLastEdited" timestamps were generated by the same source: the gallery database.
            //
            // Multiple instances of the gallery running simultaneously will have slightly different local machine times.
            // Therefore, one source must generate all "RegistrationLastEdited" timestamps because otherwise there will be slight
            // discrepancies in "RegistrationLastEdited" which can lead to registrations being read out of order by the Db2Catalog
            // cursor and silently skipped.
            //
            // Note that UPDATE(RegistrationLastEdited) is true when a row is inserted for the first time, so we must add an
            // INSERTED.RegistrationLastEdited IS NOT NULL check to the UPDATE statement.

            Sql(@"
CREATE TRIGGER [dbo].[RegistrationLastEditedTrigger] ON [dbo].[PackageRegistrations]
AFTER INSERT, UPDATE
AS
BEGIN
    IF (UPDATE(RegistrationLastEdited))
    BEGIN
        UPDATE [dbo].[PackageRegistrations]
        SET RegistrationLastEdited = GETUTCDATE()
        FROM INSERTED
        WHERE [dbo].[PackageRegistrations].[Key] = INSERTED.[Key] AND INSERTED.RegistrationLastEdited IS NOT NULL
    END
END");
        }

        public override void Down()
        {
            Sql(@"DROP TRIGGER [dbo].[RegistrationLastEditedTrigger]");
            DropIndex("dbo.PackageRegistrations", "IX_PackageRegistrations_RegistrationLastEdited");
            DropColumn("dbo.PackageRegistrations", "RegistrationLastEdited");
        }
    }
}
