//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgTests.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCatalogEntries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCatalogEntries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NgTests.Data.TestCatalogEntries", typeof(TestCatalogEntries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;record&quot;: {
        ///    &quot;id&quot;: &quot;OtherPackage&quot;,
        ///    &quot;version&quot;: &quot;1.0.0&quot;,
        ///    &quot;hash&quot;: &quot;Cj01MWn4xDwYEcApDHqrR3hCzHv0eDWiOO9TQUA46055TdDBac2FVgITPgtoEERoP5Y1jYSPtfoV/lvpmd4G1Q==&quot;,
        ///    &quot;packageRecord&quot;: [
        ///      {
        ///        &quot;key&quot;: 1,
        ///        &quot;packageRegistrationKey&quot;: 1,
        ///        &quot;created&quot;: &quot;2015-01-01T01:01:01.827Z&quot;,
        ///        &quot;description&quot;: &quot;Package&quot;,
        ///        &quot;downloadCount&quot;: 1464,
        ///        &quot;hashAlgorithm&quot;: &quot;SHA512&quot;,
        ///        &quot;hash&quot;: &quot;Cj01MWn4xDwYEcApDHqrR3hCzHv0eDWiOO9TQUA46055TdDBac2FVgITPgtoEERoP5Y1jYSPtfoV/lv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteAuditRecordForOtherPackage100 {
            get {
                return ResourceManager.GetString("DeleteAuditRecordForOtherPackage100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/page0.json&quot;,
        ///  &quot;@type&quot;: &quot;CatalogPage&quot;,
        ///  &quot;commitId&quot;: &quot;8a9e7694-73d4-4775-9b7a-20aa59b9773e&quot;,
        ///  &quot;commitTimeStamp&quot;: &quot;2017-02-08T17:18:55.3335317Z&quot;,
        ///  &quot;count&quot;: 3,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;http://tempuri.org/data/2017.02.08.17.16.18/mypackage.3.0.0.json&quot;,
        ///      &quot;@type&quot;: &quot;nuget:PackageDetails&quot;,
        ///      &quot;commitId&quot;: &quot;0d1d02f5-4800-4c69-96e1-2daaf560edc4&quot;,
        ///      &quot;commitTimeStamp&quot;: &quot;2017-02-08T17:16:18.5448099Z&quot;,
        ///      &quot;nuget:id&quot;: &quot;mypackage&quot;,
        ///      &quot;nuget:version&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogPageForMyPackage_Option1 {
            get {
                return ResourceManager.GetString("TestCatalogPageForMyPackage_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/page0.json&quot;,
        ///  &quot;@type&quot;: &quot;CatalogPage&quot;,
        ///  &quot;commitId&quot;: &quot;8a9e7694-73d4-4775-9b7a-20aa59b9773e&quot;,
        ///  &quot;commitTimeStamp&quot;: &quot;2017-02-08T17:18:55.3335317Z&quot;,
        ///  &quot;count&quot;: 3,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;http://tempuri.org/data/2017.02.08.16.49.59/mypackage.3.0.0.json&quot;,
        ///      &quot;@type&quot;: &quot;nuget:PackageDetails&quot;,
        ///      &quot;commitId&quot;: &quot;d6f4acc0-73c4-4c34-9c92-e1484e749314&quot;,
        ///      &quot;commitTimeStamp&quot;: &quot;2017-02-08T16:49:59.6916605Z&quot;,
        ///      &quot;nuget:id&quot;: &quot;mypackage&quot;,
        ///      &quot;nuget:version&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogPageForMyPackage_Option2 {
            get {
                return ResourceManager.GetString("TestCatalogPageForMyPackage_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;@id&quot;: &quot;http://tempuri.org/data/2017.02.08.16.49.48/mypackage.3.0.0.json&quot;,
        ///	&quot;@type&quot;: [&quot;PackageDetails&quot;,
        ///	&quot;catalog:Permalink&quot;],
        ///	&quot;authors&quot;: &quot;NuGet&quot;,
        ///	&quot;catalog:commitId&quot;: &quot;51ca9169-a861-4e00-8243-7de49c625da6&quot;,
        ///	&quot;catalog:commitTimeStamp&quot;: &quot;2017-02-08T16:49:48.2383888Z&quot;,
        ///	&quot;created&quot;: &quot;2017-02-08T16:48:56.567Z&quot;,
        ///	&quot;description&quot;: &quot;My package&quot;,
        ///	&quot;id&quot;: &quot;mypackage&quot;,
        ///	&quot;isPrerelease&quot;: false,
        ///	&quot;lastEdited&quot;: &quot;2017-02-08T16:48:56.567Z&quot;,
        ///	&quot;listed&quot;: false,
        ///	&quot;packageHash&quot;: &quot;iGbp+M2f6KbJruB1Y3rUtPpZ6mUsTLT7fvGT1QJcmkD8QNqS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageMyPackageCreated {
            get {
                return ResourceManager.GetString("TestCatalogStorageMyPackageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;@id&quot;: &quot;http://tempuri.org/data/2017.02.08.17.16.18/mypackage.3.0.0.json&quot;,
        ///	&quot;@type&quot;: [&quot;PackageDetails&quot;,
        ///	&quot;catalog:Permalink&quot;],
        ///	&quot;authors&quot;: &quot;NuGet&quot;,
        ///	&quot;catalog:commitId&quot;: &quot;0d1d02f5-4800-4c69-96e1-2daaf560edc4&quot;,
        ///	&quot;catalog:commitTimeStamp&quot;: &quot;2017-02-08T17:16:18.5448099Z&quot;,
        ///	&quot;created&quot;: &quot;2017-02-08T16:48:56.567Z&quot;,
        ///	&quot;description&quot;: &quot;My package&quot;,
        ///	&quot;id&quot;: &quot;mypackage&quot;,
        ///	&quot;isPrerelease&quot;: false,
        ///	&quot;lastEdited&quot;: &quot;2017-02-08T17:15:40.4Z&quot;,
        ///	&quot;listed&quot;: true,
        ///	&quot;packageHash&quot;: &quot;iGbp+M2f6KbJruB1Y3rUtPpZ6mUsTLT7fvGT1QJcmkD8QNqSZXe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageMyPackageListed {
            get {
                return ResourceManager.GetString("TestCatalogStorageMyPackageListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;@id&quot;: &quot;http://tempuri.org/data/2017.02.08.16.49.59/mypackage.3.0.0.json&quot;,
        ///	&quot;@type&quot;: [&quot;PackageDetails&quot;,
        ///	&quot;catalog:Permalink&quot;],
        ///	&quot;authors&quot;: &quot;NuGet&quot;,
        ///	&quot;catalog:commitId&quot;: &quot;d6f4acc0-73c4-4c34-9c92-e1484e749314&quot;,
        ///	&quot;catalog:commitTimeStamp&quot;: &quot;2017-02-08T16:49:59.6916605Z&quot;,
        ///	&quot;created&quot;: &quot;2017-02-08T16:48:56.567Z&quot;,
        ///	&quot;description&quot;: &quot;My package&quot;,
        ///	&quot;id&quot;: &quot;mypackage&quot;,
        ///	&quot;isPrerelease&quot;: false,
        ///	&quot;lastEdited&quot;: &quot;2017-02-08T16:48:56.567Z&quot;,
        ///	&quot;listed&quot;: false,
        ///	&quot;packageHash&quot;: &quot;iGbp+M2f6KbJruB1Y3rUtPpZ6mUsTLT7fvGT1QJcmkD8QNqS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageMyPackageUnlisted {
            get {
                return ResourceManager.GetString("TestCatalogStorageMyPackageUnlisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/index.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;CatalogRoot&quot;,
        ///    &quot;AppendOnlyCatalog&quot;,
        ///    &quot;Permalink&quot;
        ///  ],
        ///  &quot;commitId&quot;: &quot;afc8c1f4-486e-4142-b3ec-cf5841eb8883&quot;,
        ///  &quot;commitTimeStamp&quot;: &quot;2015-10-13T06:40:07.7850657Z&quot;,
        ///  &quot;count&quot;: 1,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;http://tempuri.org/page0.json&quot;,
        ///      &quot;@type&quot;: &quot;CatalogPage&quot;,
        ///      &quot;commitId&quot;: &quot;afc8c1f4-486e-4142-b3ec-cf5841eb8883&quot;,
        ///      &quot;commitTimeStamp&quot;: &quot;2015-10-13T06:40:07.7850657Z&quot;,
        ///      &quot;count&quot;: 4
        ///    }
        ///  ],
        ///  &quot;nuget:las [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesAndDeleteIndex {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesAndDeleteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/page0.json&quot;,
        ///  &quot;@type&quot;: &quot;CatalogPage&quot;,
        ///  &quot;commitId&quot;: &quot;afc8c1f4-486e-4142-b3ec-cf5841eb8883&quot;,
        ///  &quot;commitTimeStamp&quot;: &quot;2015-10-13T06:40:07.7850657Z&quot;,
        ///  &quot;count&quot;: 4,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;http://tempuri.org/data/2015.10.12.10.08.54/unlistedpackage.1.0.0.json&quot;,
        ///      &quot;@type&quot;: &quot;nuget:PackageDetails&quot;,
        ///      &quot;commitId&quot;: &quot;9a37734f-1960-4c07-8934-c8bc797e35c1&quot;,
        ///      &quot;commitTimeStamp&quot;: &quot;2015-10-12T10:08:54.1506742Z&quot;,
        ///      &quot;nuget:id&quot;: &quot;UnlistedPackage&quot;,
        ///      &quot;nuge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesAndDeletePage {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesAndDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/index.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;CatalogRoot&quot;,
        ///    &quot;AppendOnlyCatalog&quot;,
        ///    &quot;Permalink&quot;
        ///  ],
        ///  &quot;commitId&quot;: &quot;8a9e7694-73d4-4775-9b7a-20aa59b9773e&quot;,
        ///  &quot;commitTimeStamp&quot;: &quot;2015-10-12T10:08:55.3335317Z&quot;,
        ///  &quot;count&quot;: 1,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;http://tempuri.org/page0.json&quot;,
        ///      &quot;@type&quot;: &quot;CatalogPage&quot;,
        ///      &quot;commitId&quot;: &quot;8a9e7694-73d4-4775-9b7a-20aa59b9773e&quot;,
        ///      &quot;commitTimeStamp&quot;: &quot;2015-10-12T10:08:55.3335317Z&quot;,
        ///      &quot;count&quot;: 3
        ///    }
        ///  ],
        ///  &quot;nuget:las [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesIndex {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/data/2015.10.12.10.08.54/listedpackage.1.0.0.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;NuGet&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;9a37734f-1960-4c07-8934-c8bc797e35c1&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2015-10-12T10:08:54.1506742Z&quot;,
        ///  &quot;created&quot;: &quot;2015-01-01T00:00:00Z&quot;,
        ///  &quot;description&quot;: &quot;Package description.&quot;,
        ///  &quot;id&quot;: &quot;ListedPackage&quot;,
        ///  &quot;isPrerelease&quot;: false,
        ///  &quot;lastEdited&quot;: &quot;2015-01-01T00:00:00Z&quot;,
        ///  &quot;licenseNames&quot;: &quot;&quot;,
        ///  &quot;licenseRepor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesListedPackage100 {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesListedPackage100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/data/2015.10.12.10.08.55/listedpackage.1.0.1.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;NuGet&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;8a9e7694-73d4-4775-9b7a-20aa59b9773e&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2015-10-12T10:08:55.3335317Z&quot;,
        ///  &quot;created&quot;: &quot;2015-01-01T00:00:00Z&quot;,
        ///  &quot;description&quot;: &quot;Package description.&quot;,
        ///  &quot;id&quot;: &quot;ListedPackage&quot;,
        ///  &quot;isPrerelease&quot;: false,
        ///  &quot;lastEdited&quot;: &quot;2015-01-01T00:00:00Z&quot;,
        ///  &quot;licenseNames&quot;: &quot;&quot;,
        ///  &quot;licenseRepor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesListedPackage101 {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesListedPackage101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/data/2015.10.13.06.40.07/otherpackage.1.0.0.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDelete&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;catalog:commitId&quot;: &quot;afc8c1f4-486e-4142-b3ec-cf5841eb8883&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2015-10-13T06:40:07.7850657Z&quot;,
        ///  &quot;id&quot;: &quot;OtherPackage&quot;,
        ///  &quot;originalId&quot;: &quot;OtherPackage&quot;,
        ///  &quot;published&quot;: &quot;2015-01-01T01:01:01.0748028Z&quot;,
        ///  &quot;version&quot;: &quot;1.0.0&quot;,
        ///  &quot;@context&quot;: {
        ///    &quot;@vocab&quot;: &quot;http://schema.nuget.org/schema#&quot;,
        ///    &quot;catalog&quot;: &quot;http://schema.nuget.org/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesOtherPackage100 {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesOtherPackage100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/page0.json&quot;,
        ///  &quot;@type&quot;: &quot;CatalogPage&quot;,
        ///  &quot;commitId&quot;: &quot;8a9e7694-73d4-4775-9b7a-20aa59b9773e&quot;,
        ///  &quot;commitTimeStamp&quot;: &quot;2015-10-12T10:08:55.3335317Z&quot;,
        ///  &quot;count&quot;: 3,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;@id&quot;: &quot;http://tempuri.org/data/2015.10.12.10.08.54/unlistedpackage.1.0.0.json&quot;,
        ///      &quot;@type&quot;: &quot;nuget:PackageDetails&quot;,
        ///      &quot;commitId&quot;: &quot;9a37734f-1960-4c07-8934-c8bc797e35c1&quot;,
        ///      &quot;commitTimeStamp&quot;: &quot;2015-10-12T10:08:54.1506742Z&quot;,
        ///      &quot;nuget:id&quot;: &quot;UnlistedPackage&quot;,
        ///      &quot;nuge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesPage {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;http://tempuri.org/data/2015.10.12.10.08.54/unlistedpackage.1.0.0.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;NuGet&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;9a37734f-1960-4c07-8934-c8bc797e35c1&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2015-10-12T10:08:54.1506742Z&quot;,
        ///  &quot;created&quot;: &quot;2015-01-01T00:00:00Z&quot;,
        ///  &quot;description&quot;: &quot;Package description.&quot;,
        ///  &quot;id&quot;: &quot;UnlistedPackage&quot;,
        ///  &quot;isPrerelease&quot;: false,
        ///  &quot;lastEdited&quot;: &quot;2015-01-01T00:00:00Z&quot;,
        ///  &quot;licenseNames&quot;: &quot;&quot;,
        ///  &quot;licenseR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCatalogStorageWithThreePackagesUnlistedPackage100 {
            get {
                return ResourceManager.GetString("TestCatalogStorageWithThreePackagesUnlistedPackage100", resourceCulture);
            }
        }
    }
}
