// <auto-generated />
namespace NuGetGallery.Areas.Admin
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PackageInfoIsOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PackageInfoIsOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201602191039005_PackageInfoIsOptional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
