//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Protocol.Catalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Protocol.Catalog.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/index.json&quot;,&quot;@type&quot;:[&quot;CatalogRoot&quot;,&quot;AppendOnlyCatalog&quot;,&quot;Permalink&quot;],&quot;commitId&quot;:&quot;57de6c98-d4c6-4a24-95b9-1829c5013985&quot;,&quot;commitTimeStamp&quot;:&quot;2017-11-06T19:30:56.0421411Z&quot;,&quot;count&quot;:2945,&quot;nuget:lastCreated&quot;:&quot;2017-11-06T19:30:30.19Z&quot;,&quot;nuget:lastDeleted&quot;:&quot;2017-11-06T19:27:45.3684766Z&quot;,&quot;nuget:lastEdited&quot;:&quot;2017-11-06T19:02:37.87Z&quot;,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/page0.json&quot;,&quot;@type&quot;:&quot;CatalogPage&quot;,&quot;commitId&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;commitTimeSt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CatalogIndex {
            get {
                return ResourceManager.GetString("CatalogIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/index.json.
        /// </summary>
        public static string CatalogIndexUrl {
            get {
                return ResourceManager.GetString("CatalogIndexUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2016.02.21.11.06.01/dingu.generic.repo.ef7.1.0.0-beta2.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;3344hp&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;eddb29f8-32c6-41da-8928-0940927a708b&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2016-02-21T11:06:01.8896907Z&quot;,
        ///  &quot;created&quot;: &quot;2016-02-21T11:05:37.54Z&quot;,
        ///  &quot;description&quot;: &quot;Dingu.Generic.Repo.EF7 Class Library&quot;,
        ///  &quot;frameworkAssemblyGroup&quot;: {
        ///    &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CatalogLeafInvalidDependencyVersionRange {
            get {
                return ResourceManager.GetString("CatalogLeafInvalidDependencyVersionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/data/2016.02.21.11.06.01/dingu.generic.repo.ef7.1.0.0-beta2.json.
        /// </summary>
        public static string CatalogLeafInvalidDependencyVersionRangeUrl {
            get {
                return ResourceManager.GetString("CatalogLeafInvalidDependencyVersionRangeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/12.0.1.json&quot;,&quot;@type&quot;:&quot;nuget:PackageDetails&quot;,&quot;commitTimeStamp&quot;:&quot;2019-10-10T00:00:00+00:00&quot;,&quot;nuget:id&quot;:&quot;Newtonsoft.Json&quot;,&quot;nuget:version&quot;:&quot;12.0.1&quot;}.
        /// </summary>
        public static string CatalogLeafItem {
            get {
                return ResourceManager.GetString("CatalogLeafItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/page2944.json&quot;,&quot;@type&quot;:&quot;CatalogPage&quot;,&quot;commitId&quot;:&quot;f241ce46-35ba-44c2-bd72-790eb44539a5&quot;,&quot;commitTimeStamp&quot;:&quot;2017-11-06T22:07:49.3270578Z&quot;,&quot;count&quot;:218,&quot;parent&quot;:&quot;https://api.nuget.org/v3/catalog0/index.json&quot;,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/data/2017.11.06.22.07.49/dotnettency.container.1.3.2.json&quot;,&quot;@type&quot;:&quot;nuget:PackageDetails&quot;,&quot;commitId&quot;:&quot;f241ce46-35ba-44c2-bd72-790eb44539a5&quot;,&quot;commitTimeStamp&quot;:&quot;2017-11-06T22:07:49.3270578Z&quot;,&quot;nuget:id&quot;:&quot;Dotnettency.Co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CatalogPage {
            get {
                return ResourceManager.GetString("CatalogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/page2944.json.
        /// </summary>
        public static string CatalogPageUrl {
            get {
                return ResourceManager.GetString("CatalogPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2017.11.06.19.29.03/microsoft.azure.iot.edge.function.0.3.0.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDelete&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;catalog:commitId&quot;: &quot;b429c4e3-5127-4430-9cc8-74927c9c3886&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2017-11-06T19:29:03.6198426Z&quot;,
        ///  &quot;id&quot;: &quot;Microsoft.Azure.IoT.Edge.Function&quot;,
        ///  &quot;originalId&quot;: &quot;Microsoft.Azure.IoT.Edge.Function&quot;,
        ///  &quot;published&quot;: &quot;2017-11-06T19:27:45.3684766Z&quot;,
        ///  &quot;version&quot;: &quot;0.3.0&quot;,
        ///  &quot;@context&quot;: {
        ///    &quot;@vocab&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PackageDeleteCatalogLeaf {
            get {
                return ResourceManager.GetString("PackageDeleteCatalogLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/data/2017.11.06.19.29.03/microsoft.azure.iot.edge.function.0.3.0.json.
        /// </summary>
        public static string PackageDeleteCatalogLeafUrl {
            get {
                return ResourceManager.GetString("PackageDeleteCatalogLeafUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2017.11.06.22.07.49/dotnettency.container.1.3.2.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;Darrell Tunnell&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;f241ce46-35ba-44c2-bd72-790eb44539a5&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2017-11-06T22:07:49.3270578Z&quot;,
        ///  &quot;created&quot;: &quot;2017-11-06T22:06:53.64Z&quot;,
        ///  &quot;description&quot;: &quot;Container support, for the dotnettency Mutlitenancy library for dotnet standard compatible applications.&quot;,
        ///  &quot;id&quot;: &quot;Do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PackageDetailsCatalogLeaf {
            get {
                return ResourceManager.GetString("PackageDetailsCatalogLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/data/2017.11.06.22.07.49/dotnettency.container.1.3.2.json.
        /// </summary>
        public static string PackageDetailsCatalogLeafUrl {
            get {
                return ResourceManager.GetString("PackageDetailsCatalogLeafUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2015.02.01.06.22.45/antixss.4.0.1.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;Microsoft&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;b3f4fc8a-7522-42a3-8fee-a91d5488c0b1&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2015-02-01T06:22:45.8488496Z&quot;,
        ///  &quot;created&quot;: &quot;2011-01-07T07:49:50.307Z&quot;,
        ///  &quot;description&quot;: &quot;AntiXSS is an encoding library which uses a safe list approach to encoding. It provides Html, XML, Url, Form, LDAP, CSS, JScript and VBScr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PackageDetailsLeafWithRequireLicenseAcceptance {
            get {
                return ResourceManager.GetString("PackageDetailsLeafWithRequireLicenseAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/data/2015.02.01.06.22.45/antixss.4.0.1.json.
        /// </summary>
        public static string PackageDetailsLeafWithRequireLicenseAcceptanceUrl {
            get {
                return ResourceManager.GetString("PackageDetailsLeafWithRequireLicenseAcceptanceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/microbuild.core/index.json&quot;,&quot;@type&quot;:[&quot;catalog:CatalogRoot&quot;,&quot;PackageRegistration&quot;,&quot;catalog:Permalink&quot;],&quot;commitId&quot;:&quot;bef2767e-f5ae-4713-b5fc-510945bacdf9&quot;,&quot;commitTimeStamp&quot;:&quot;2018-11-26T19:53:07.9393299Z&quot;,&quot;count&quot;:1,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/microbuild.core/index.json#page/0.1.1/0.3.1&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;bef2767e-f5ae-4713-b5fc-510945bacdf9&quot;,&quot;commitTimeStamp&quot;:&quot;2018-11-26T19:53:07.9393299Z&quot;,&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationIndexInlinedItems {
            get {
                return ResourceManager.GetString("RegistrationIndexInlinedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/registration3-gz-semver2/microbuild.core/index.json.
        /// </summary>
        public static string RegistrationIndexInlinedItemsUrl {
            get {
                return ResourceManager.GetString("RegistrationIndexInlinedItemsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/ravendb.database/index.json&quot;,&quot;@type&quot;:[&quot;catalog:CatalogRoot&quot;,&quot;PackageRegistration&quot;,&quot;catalog:Permalink&quot;],&quot;commitId&quot;:&quot;11185fcc-dd1b-461f-b5c6-0c06068c0a6d&quot;,&quot;commitTimeStamp&quot;:&quot;2018-11-07T08:01:25.5414875Z&quot;,&quot;count&quot;:19,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/ravendb.database/page/1.0.728-unstable/1.0.965-unstable.json&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;11185fcc-dd1b-461f-b5c6-0c06068c0a6d&quot;,&quot;commitTimeStamp&quot;:&quot;2018-11-07T08 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationIndexWithoutInlinedItems {
            get {
                return ResourceManager.GetString("RegistrationIndexWithoutInlinedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/registration3-gz-semver2/ravendb.database/index.json.
        /// </summary>
        public static string RegistrationIndexWithoutInlinedItemsUrl {
            get {
                return ResourceManager.GetString("RegistrationIndexWithoutInlinedItemsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/12.0.1.json&quot;,&quot;@type&quot;:[&quot;Package&quot;,&quot;http://schema.nuget.org/catalog#Permalink&quot;],&quot;catalogEntry&quot;:&quot;https://api.nuget.org/v3/catalog0/data/2018.11.27.18.15.55/newtonsoft.json.12.0.1.json&quot;,&quot;listed&quot;:true,&quot;packageContent&quot;:&quot;https://api.nuget.org/v3-flatcontainer/newtonsoft.json/12.0.1/newtonsoft.json.12.0.1.nupkg&quot;,&quot;published&quot;:&quot;2018-11-27T18:11:37.08+00:00&quot;,&quot;registration&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/index.js [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationLeafListed {
            get {
                return ResourceManager.GetString("RegistrationLeafListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/12.0.1.json.
        /// </summary>
        public static string RegistrationLeafListedUrl {
            get {
                return ResourceManager.GetString("RegistrationLeafListedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/microbuild.core/0.1.1.json&quot;,&quot;@type&quot;:[&quot;Package&quot;,&quot;http://schema.nuget.org/catalog#Permalink&quot;],&quot;catalogEntry&quot;:&quot;https://api.nuget.org/v3/catalog0/data/2018.11.13.04.43.04/microbuild.core.0.1.1.json&quot;,&quot;listed&quot;:false,&quot;packageContent&quot;:&quot;https://api.nuget.org/v3-flatcontainer/microbuild.core/0.1.1/microbuild.core.0.1.1.nupkg&quot;,&quot;published&quot;:&quot;1900-01-01T00:00:00+00:00&quot;,&quot;registration&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/microbuild.core/index.json&quot;,&quot;@ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationLeafUnlisted {
            get {
                return ResourceManager.GetString("RegistrationLeafUnlisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/registration3-gz-semver2/microbuild.core/0.1.1.json.
        /// </summary>
        public static string RegistrationLeafUnlistedUrl {
            get {
                return ResourceManager.GetString("RegistrationLeafUnlistedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/ravendb.database/page/3.5.35078-unstable/3.5.35142-unstable.json&quot;,&quot;@type&quot;:&quot;catalog:CatalogPage&quot;,&quot;commitId&quot;:&quot;11185fcc-dd1b-461f-b5c6-0c06068c0a6d&quot;,&quot;commitTimeStamp&quot;:&quot;2018-11-07T08:01:25.5414875Z&quot;,&quot;count&quot;:55,&quot;lower&quot;:&quot;3.5.35078-Unstable&quot;,&quot;parent&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/ravendb.database/index.json&quot;,&quot;upper&quot;:&quot;3.5.35142-Unstable&quot;,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/registration3-gz-semver2/ravendb.database/3.5.35078-unstabl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationPage {
            get {
                return ResourceManager.GetString("RegistrationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/registration3-gz-semver2/ravendb.database/page/3.5.35078-unstable/3.5.35142-unstable.json.
        /// </summary>
        public static string RegistrationPageUrl {
            get {
                return ResourceManager.GetString("RegistrationPageUrl", resourceCulture);
            }
        }
    }
}
