//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Protocol.Catalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Protocol.Catalog.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/index.json&quot;,&quot;@type&quot;:[&quot;CatalogRoot&quot;,&quot;AppendOnlyCatalog&quot;,&quot;Permalink&quot;],&quot;commitId&quot;:&quot;57de6c98-d4c6-4a24-95b9-1829c5013985&quot;,&quot;commitTimeStamp&quot;:&quot;2017-11-06T19:30:56.0421411Z&quot;,&quot;count&quot;:2945,&quot;nuget:lastCreated&quot;:&quot;2017-11-06T19:30:30.19Z&quot;,&quot;nuget:lastDeleted&quot;:&quot;2017-11-06T19:27:45.3684766Z&quot;,&quot;nuget:lastEdited&quot;:&quot;2017-11-06T19:02:37.87Z&quot;,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/page0.json&quot;,&quot;@type&quot;:&quot;CatalogPage&quot;,&quot;commitId&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;commitTimeSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CatalogIndex {
            get {
                return ResourceManager.GetString("CatalogIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/index.json.
        /// </summary>
        internal static string CatalogIndexUrl {
            get {
                return ResourceManager.GetString("CatalogIndexUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/page2944.json&quot;,&quot;@type&quot;:&quot;CatalogPage&quot;,&quot;commitId&quot;:&quot;f241ce46-35ba-44c2-bd72-790eb44539a5&quot;,&quot;commitTimeStamp&quot;:&quot;2017-11-06T22:07:49.3270578Z&quot;,&quot;count&quot;:218,&quot;parent&quot;:&quot;https://api.nuget.org/v3/catalog0/index.json&quot;,&quot;items&quot;:[{&quot;@id&quot;:&quot;https://api.nuget.org/v3/catalog0/data/2017.11.06.22.07.49/dotnettency.container.1.3.2.json&quot;,&quot;@type&quot;:&quot;nuget:PackageDetails&quot;,&quot;commitId&quot;:&quot;f241ce46-35ba-44c2-bd72-790eb44539a5&quot;,&quot;commitTimeStamp&quot;:&quot;2017-11-06T22:07:49.3270578Z&quot;,&quot;nuget:id&quot;:&quot;Dotnettency.Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CatalogPage {
            get {
                return ResourceManager.GetString("CatalogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/page2944.json.
        /// </summary>
        internal static string CatalogPageUrl {
            get {
                return ResourceManager.GetString("CatalogPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2017.11.06.19.29.03/microsoft.azure.iot.edge.function.0.3.0.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDelete&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;catalog:commitId&quot;: &quot;b429c4e3-5127-4430-9cc8-74927c9c3886&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2017-11-06T19:29:03.6198426Z&quot;,
        ///  &quot;id&quot;: &quot;Microsoft.Azure.IoT.Edge.Function&quot;,
        ///  &quot;originalId&quot;: &quot;Microsoft.Azure.IoT.Edge.Function&quot;,
        ///  &quot;published&quot;: &quot;2017-11-06T19:27:45.3684766Z&quot;,
        ///  &quot;version&quot;: &quot;0.3.0&quot;,
        ///  &quot;@context&quot;: {
        ///    &quot;@vocab&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PackageDeleteCatalogLeaf {
            get {
                return ResourceManager.GetString("PackageDeleteCatalogLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/data/2017.11.06.19.29.03/microsoft.azure.iot.edge.function.0.3.0.json.
        /// </summary>
        internal static string PackageDeleteCatalogLeafUrl {
            get {
                return ResourceManager.GetString("PackageDeleteCatalogLeafUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@id&quot;: &quot;https://api.nuget.org/v3/catalog0/data/2017.11.06.22.07.49/dotnettency.container.1.3.2.json&quot;,
        ///  &quot;@type&quot;: [
        ///    &quot;PackageDetails&quot;,
        ///    &quot;catalog:Permalink&quot;
        ///  ],
        ///  &quot;authors&quot;: &quot;Darrell Tunnell&quot;,
        ///  &quot;catalog:commitId&quot;: &quot;f241ce46-35ba-44c2-bd72-790eb44539a5&quot;,
        ///  &quot;catalog:commitTimeStamp&quot;: &quot;2017-11-06T22:07:49.3270578Z&quot;,
        ///  &quot;created&quot;: &quot;2017-11-06T22:06:53.64Z&quot;,
        ///  &quot;description&quot;: &quot;Container support, for the dotnettency Mutlitenancy library for dotnet standard compatible applications.&quot;,
        ///  &quot;id&quot;: &quot;Do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PackageDetailsCatalogLeaf {
            get {
                return ResourceManager.GetString("PackageDetailsCatalogLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nuget.org/v3/catalog0/data/2017.11.06.22.07.49/dotnettency.container.1.3.2.json.
        /// </summary>
        internal static string PackageDetailsCatalogLeafUrl {
            get {
                return ResourceManager.GetString("PackageDetailsCatalogLeafUrl", resourceCulture);
            }
        }
    }
}
