// Knockout JavaScript library v1.3.0ctp
// (c) Steven Sanderson - http://knockoutjs.com/
// License: MIT (http://www.opensource.org/licenses/mit-license.php)

(function(window,undefined){ 
function b(d){throw d;}var l=void 0,n=null,q=window.ko={};q.b=function(d,e){for(var c=d.split("."),a=window,f=0;f<c.length-1;f++)a=a[c[f]];a[c[c.length-1]]=e};q.j=function(d,e,c){d[e]=c};
q.a=new function(){function d(a,f){if(a.tagName!="INPUT"||!a.type)return!1;if(f.toLowerCase()!="click")return!1;var g=a.type.toLowerCase();return g=="checkbox"||g=="radio"}var e=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,c={click:1,dblclick:1,mousedown:1,mouseup:1,mousemove:1,mouseover:1,mouseout:1,mouseenter:1,mouseleave:1};return{ta:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],o:function(a,f){for(var g=0,c=a.length;g<c;g++)f(a[g])},h:function(a,f){if(typeof a.indexOf=="function")return a.indexOf(f);
for(var g=0,c=a.length;g<c;g++)if(a[g]===f)return g;return-1},Oa:function(a,f,g){for(var c=0,d=a.length;c<d;c++)if(f.call(g,a[c]))return a[c];return n},U:function(a,f){var g=q.a.h(a,f);g>=0&&a.splice(g,1)},T:function(a,f){for(var a=a||[],g=[],c=0,d=a.length;c<d;c++)g.push(f(a[c]));return g},S:function(a,f){for(var a=a||[],g=[],c=0,d=a.length;c<d;c++)f(a[c])&&g.push(a[c]);return g},F:function(a,f){for(var g=0,c=f.length;g<c;g++)a.push(f[g]);return a},I:function(a){for(;a.firstChild;)q.removeNode(a.firstChild)},
ha:function(a,f){q.a.I(a);f&&q.a.o(f,function(f){a.appendChild(f)})},Ca:function(a,f){var g=a.nodeType?[a]:a;if(g.length>0){for(var c=g[0],d=c.parentNode,e=0,k=f.length;e<k;e++)d.insertBefore(f[e],c);e=0;for(k=g.length;e<k;e++)q.removeNode(g[e])}},Ea:function(a,f){navigator.userAgent.indexOf("MSIE 6")>=0?a.setAttribute("selected",f):a.selected=f},t:function(a){return(a||"").replace(e,"")},wb:function(a,f){for(var g=[],c=(a||"").split(f),d=0,e=c.length;d<e;d++){var k=q.a.t(c[d]);k!==""&&g.push(k)}return g},
tb:function(a,f){a=a||"";return f.length>a.length?!1:a.substring(0,f.length)===f},Ya:function(a){for(var f=Array.prototype.slice.call(arguments,1),g="return ("+a+")",c=0;c<f.length;c++)f[c]&&typeof f[c]=="object"&&(g="with(sc["+c+"]) { "+g+" } ");return(new Function("sc",g))(f)},Wa:function(a,f){if(f.compareDocumentPosition)return(f.compareDocumentPosition(a)&16)==16;for(;a!=n;){if(a==f)return!0;a=a.parentNode}return!1},Z:function(a){return q.a.Wa(a,document)},D:function(a,f,g){if(typeof jQuery!=
"undefined"){if(d(a,f))var c=g,g=function(a,f){var g=this.checked;if(f)this.checked=f.Qa!==!0;c.call(this,a);this.checked=g};jQuery(a).bind(f,g)}else typeof a.addEventListener=="function"?a.addEventListener(f,g,!1):typeof a.attachEvent!="undefined"?a.attachEvent("on"+f,function(f){g.call(a,f)}):b(Error("Browser doesn't support addEventListener or attachEvent"))},Ia:function(a,f){(!a||!a.nodeType)&&b(Error("element must be a DOM node when calling triggerEvent"));if(typeof jQuery!="undefined"){var g=
[];d(a,f)&&g.push({Qa:a.checked});jQuery(a).trigger(f,g)}else if(typeof document.createEvent=="function")typeof a.dispatchEvent=="function"?(g=document.createEvent(f in c?"MouseEvents":"HTMLEvents"),g.initEvent(f,!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,a),a.dispatchEvent(g)):b(Error("The supplied element doesn't support dispatchEvent"));else if(typeof a.fireEvent!="undefined"){if(f=="click"&&a.tagName=="INPUT"&&(a.type.toLowerCase()=="checkbox"||a.type.toLowerCase()=="radio"))a.checked=a.checked!==!0;
a.fireEvent("on"+f)}else b(Error("Browser doesn't support triggering events"))},d:function(a){return q.M(a)?a():a},Va:function(a,f){return q.a.h((a.className||"").split(/\s+/),f)>=0},Ha:function(a,f,g){var c=q.a.Va(a,f);if(g&&!c)a.className=(a.className||"")+" "+f;else if(c&&!g){for(var g=(a.className||"").split(/\s+/),c="",d=0;d<g.length;d++)g[d]!=f&&(c+=g[d]+" ");a.className=q.a.t(c)}},outerHTML:function(a){var f=a.outerHTML;if(typeof f=="string")return f;f=window.document.createElement("div");
f.appendChild(a.cloneNode(!0));return f.innerHTML},ob:function(a,f){for(var a=q.a.d(a),f=q.a.d(f),g=[],c=a;c<=f;c++)g.push(c);return g},da:function(a){for(var f=[],g=0,c=a.length;g<c;g++)f.push(a[g]);return f},ba:/MSIE 6/i.test(navigator.userAgent),fb:/MSIE 7/i.test(navigator.userAgent),ua:function(a,f){for(var g=q.a.da(a.getElementsByTagName("INPUT")).concat(q.a.da(a.getElementsByTagName("TEXTAREA"))),c=typeof f=="string"?function(a){return a.name===f}:function(a){return f.test(a.name)},d=[],e=g.length-
1;e>=0;e--)c(g[e])&&d.push(g[e]);return d},lb:function(a){return typeof a=="string"&&(a=q.a.t(a))?window.JSON&&window.JSON.parse?window.JSON.parse(a):(new Function("return "+a))():n},ja:function(a){(typeof JSON=="undefined"||typeof JSON.stringify=="undefined")&&b(Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js"));return JSON.stringify(q.a.d(a))},
mb:function(a,f,g){var g=g||{},c=g.params||{},d=g.includeFields||this.ta,e=a;if(typeof a=="object"&&a.tagName=="FORM")for(var e=a.action,k=d.length-1;k>=0;k--)for(var m=q.a.ua(a,d[k]),o=m.length-1;o>=0;o--)c[m[o].name]=m[o].value;var f=q.a.d(f),p=document.createElement("FORM");p.style.display="none";p.action=e;p.method="post";for(var r in f)a=document.createElement("INPUT"),a.name=r,a.value=q.a.ja(q.a.d(f[r])),p.appendChild(a);for(r in c)a=document.createElement("INPUT"),a.name=r,a.value=c[r],p.appendChild(a);
document.body.appendChild(p);g.submitter?g.submitter(p):p.submit();setTimeout(function(){p.parentNode.removeChild(p)},0)}}};q.b("ko.utils",q.a);q.b("ko.utils.arrayForEach",q.a.o);q.b("ko.utils.arrayFirst",q.a.Oa);q.b("ko.utils.arrayFilter",q.a.S);q.b("ko.utils.arrayGetDistinctValues",q.a.vb);q.b("ko.utils.arrayIndexOf",q.a.h);q.b("ko.utils.arrayMap",q.a.T);q.b("ko.utils.arrayPushAll",q.a.F);q.b("ko.utils.arrayRemoveItem",q.a.U);q.b("ko.utils.fieldsIncludedWithJsonPost",q.a.ta);
q.b("ko.utils.getFormFields",q.a.ua);q.b("ko.utils.postJson",q.a.mb);q.b("ko.utils.parseJson",q.a.lb);q.b("ko.utils.registerEventHandler",q.a.D);q.b("ko.utils.stringifyJson",q.a.ja);q.b("ko.utils.range",q.a.ob);q.b("ko.utils.toggleDomNodeCssClass",q.a.Ha);q.b("ko.utils.triggerEvent",q.a.Ia);q.b("ko.utils.unwrapObservable",q.a.d);Function.prototype.bind||(Function.prototype.bind=function(d){var e=this,c=Array.prototype.slice.call(arguments),d=c.shift();return function(){return e.apply(d,c.concat(Array.prototype.slice.call(arguments)))}});
q.a.e=new function(){var d=0,e="__ko__"+(new Date).getTime(),c={};return{get:function(a,f){var g=q.a.e.getAll(a,!1);return g===l?l:g[f]},set:function(a,f,g){g===l&&q.a.e.getAll(a,!1)===l||(q.a.e.getAll(a,!0)[f]=g)},getAll:function(a,f){var g=a[e];if(!g){if(!f)return;g=a[e]="ko"+d++;c[g]={}}return c[g]},clear:function(a){var f=a[e];f&&(delete c[f],a[e]=n)}}};
q.a.v=new function(){function d(a,f){var g=q.a.e.get(a,c);g===l&&f&&(g=[],q.a.e.set(a,c,g));return g}function e(a){var f=d(a,!1);if(f)for(var f=f.slice(0),g=0;g<f.length;g++)f[g](a);q.a.e.clear(a);typeof jQuery=="function"&&typeof jQuery.cleanData=="function"&&jQuery.cleanData([a])}var c="__ko_domNodeDisposal__"+(new Date).getTime();return{oa:function(a,f){typeof f!="function"&&b(Error("Callback must be a function"));d(a,!0).push(f)},Ba:function(a,f){var g=d(a,!1);g&&(q.a.U(g,f),g.length==0&&q.a.e.set(a,
c,l))},G:function(a){if(!(a.nodeType!=1&&a.nodeType!=9)){e(a);var f=[];q.a.F(f,a.getElementsByTagName("*"));for(var a=0,g=f.length;a<g;a++)e(f[a])}},removeNode:function(a){q.G(a);a.parentNode&&a.parentNode.removeChild(a)}}};q.G=q.a.v.G;q.removeNode=q.a.v.removeNode;q.b("ko.cleanNode",q.G);q.b("ko.removeNode",q.removeNode);q.b("ko.utils.domNodeDisposal",q.a.v);q.b("ko.utils.domNodeDisposal.addDisposeCallback",q.a.v.oa);q.b("ko.utils.domNodeDisposal.removeDisposeCallback",q.a.v.Ba);
(function(){function d(c){for(var c=c||"",a=[];c.match(e);)c=c.replace(e,function(f,g,c){g&&a.push(new document.createTextNode(g));a.push(document.createComment(c));return""});var f=q.a.t(c).toLowerCase(),g=document.createElement("div"),f=f.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!f.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!f.indexOf("<td")||!f.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];for(g.innerHTML=f[1]+c+f[2];f[0]--;)g=g.lastChild;
return a.concat(q.a.da(g.childNodes))}var e=/^(\s*)<\!--(.*?)--\>/;q.a.xa=function(c){return typeof jQuery!="undefined"?jQuery.clean([c]):d(c)};q.a.rb=function(c,a){q.a.I(c);if(a!==n&&a!==l)if(typeof a!="string"&&(a=a.toString()),typeof jQuery!="undefined")jQuery(c).html(a);else for(var f=q.a.xa(a),g=0;g<f.length;g++)c.appendChild(f[g])}})();
q.p=function(){function d(){return((1+Math.random())*4294967296|0).toString(16).substring(1)}function e(a,f){if(a)if(a.nodeType==8){var g=q.p.ya(a.nodeValue);g!=n&&f.push({Ua:a,ib:g})}else if(a.nodeType==1)for(var g=0,c=a.childNodes,d=c.length;g<d;g++)e(c[g],f)}var c={};return{ea:function(a){typeof a!="function"&&b(Error("You can only pass a function to ko.memoization.memoize()"));var f=d()+d();c[f]=a;return"<\!--[ko_memo:"+f+"]--\>"},Ka:function(a,f){var g=c[a];g===l&&b(Error("Couldn't find any memo with ID "+
a+". Perhaps it's already been unmemoized."));try{return g.apply(n,f||[]),!0}finally{delete c[a]}},La:function(a,f){var g=[];e(a,g);for(var c=0,d=g.length;c<d;c++){var j=g[c].Ua,k=[j];f&&q.a.F(k,f);q.p.Ka(g[c].ib,k);j.nodeValue="";j.parentNode&&j.parentNode.removeChild(j)}},ya:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:n}}}();q.b("ko.memoization",q.p);q.b("ko.memoization.memoize",q.p.ea);q.b("ko.memoization.unmemoize",q.p.Ka);q.b("ko.memoization.parseMemoText",q.p.ya);
q.b("ko.memoization.unmemoizeDomNodeAndDescendants",q.p.La);q.sa={};function y(d){var e=this;if(d)for(var c in d){var a=q.sa[c];typeof a=="function"&&(e=a(e,d[c]))}return e}q.b("ko.extenders",q.sa);q.ub=function(d,e){this.V=d;this.s=function(){this.eb=!0;e()}.bind(this);q.j(this,"dispose",this.s)};
q.ka=function(){var d=[];this.la=function(e,c){var a=c?e.bind(c):e,f=new q.ub(a,function(){q.a.U(d,f)});d.push(f);return f};this.J=function(e){q.a.o(d.slice(0),function(c){c&&c.eb!==!0&&c.V(e)})};this.ab=function(){return d.length};this.extend=y;q.j(this,"subscribe",this.la);q.j(this,"extend",this.extend);q.j(this,"notifySubscribers",this.J);q.j(this,"getSubscriptionsCount",this.ab)};q.wa=function(d){return typeof d.la=="function"&&typeof d.J=="function"};q.b("ko.subscribable",q.ka);
q.b("ko.isSubscribable",q.wa);q.K=function(){var d=[];return{Pa:function(e){d.push({V:e,ra:[]})},end:function(){d.pop()},Aa:function(e){q.wa(e)||b("Only subscribable things can act as dependencies");if(d.length>0){var c=d[d.length-1];q.a.h(c.ra,e)>=0||(c.ra.push(e),c.V(e))}}}}();var z={undefined:!0,"boolean":!0,number:!0,string:!0};function A(d,e){return d===n||typeof d in z?d===e:!1}
q.C=function(d){function e(){if(arguments.length>0){if(!e.equalityComparer||!e.equalityComparer(c,arguments[0]))c=arguments[0],e.J(c);return this}else return q.K.Aa(e),c}var c=d;e.u=q.C;e.Q=function(){e.J(c)};e.equalityComparer=A;q.ka.call(e);q.j(e,"valueHasMutated",e.Q);return e};q.M=function(d){return d===n||d===l||d.u===l?!1:d.u===q.C?!0:q.M(d.u)};q.N=function(d){return typeof d=="function"&&d.u===q.C?!0:typeof d=="function"&&d.u===q.l&&d.bb?!0:!1};q.b("ko.observable",q.C);
q.b("ko.isObservable",q.M);q.b("ko.isWriteableObservable",q.N);
q.kb=function(d){arguments.length==0&&(d=[]);d!==n&&d!==l&&!("length"in d)&&b(Error("The argument passed when initializing an observable array must be an array, or null, or undefined."));var e=new q.C(d);q.a.o("pop,push,reverse,shift,sort,splice,unshift".split(","),function(c){e[c]=function(){var a=e(),a=a[c].apply(a,arguments);e.Q();return a}});q.a.o(["slice"],function(c){e[c]=function(){var a=e();return a[c].apply(a,arguments)}});e.remove=function(c){for(var a=e(),f=[],g=[],d=typeof c=="function"?
c:function(a){return a===c},h=0,j=a.length;h<j;h++){var k=a[h];d(k)?g.push(k):f.push(k)}e(f);return g};e.pb=function(c){if(c===l){var a=e();e([]);return a}return!c?[]:e.remove(function(a){return q.a.h(c,a)>=0})};e.Y=function(c){for(var a=e(),f=typeof c=="function"?c:function(a){return a===c},g=a.length-1;g>=0;g--)f(a[g])&&(a[g]._destroy=!0);e.Q()};e.Ta=function(c){return c===l?e.Y(function(){return!0}):!c?[]:e.Y(function(a){return q.a.h(c,a)>=0})};e.indexOf=function(c){var a=e();return q.a.h(a,c)};
e.replace=function(c,a){var f=e.indexOf(c);f>=0&&(e()[f]=a,e.Q())};q.j(e,"remove",e.remove);q.j(e,"removeAll",e.pb);q.j(e,"destroy",e.Y);q.j(e,"destroyAll",e.Ta);q.j(e,"indexOf",e.indexOf);return e};q.b("ko.observableArray",q.kb);
q.l=function(d,e,c){function a(){q.a.o(o,function(a){a.s()});o=[]}function f(){if(h&&typeof c.disposeWhen=="function"&&c.disposeWhen())g.s();else{try{a(),q.K.Pa(function(a){o.push(a.la(f))}),i=c.owner?c.read.call(c.owner):c.read()}finally{q.K.end()}g.J(i);h=!0}}function g(){if(arguments.length>0)if(typeof c.write==="function"){var a=arguments[0];c.owner?c.write.call(c.owner,a):c.write(a)}else b("Cannot write a value to a dependentObservable unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");
else return h||f(),q.K.Aa(g),i}var i,h=!1;d&&typeof d=="object"?c=d:(c=c||{},c.read=d||c.read,c.owner=e||c.owner);typeof c.read!="function"&&b("Pass a function that returns the value of the dependentObservable");var j=typeof c.disposeWhenNodeIsRemoved=="object"?c.disposeWhenNodeIsRemoved:n,k=n;if(j){k=function(){g.s()};q.a.v.oa(j,k);var m=c.disposeWhen;c.disposeWhen=function(){return!q.a.Z(j)||typeof m=="function"&&m()}}var o=[];g.u=q.l;g.$a=function(){return o.length};g.bb=typeof c.write==="function";
g.s=function(){j&&q.a.v.Ba(j,k);a()};q.ka.call(g);c.deferEvaluation!==!0&&f();q.j(g,"dispose",g.s);q.j(g,"getDependenciesCount",g.$a);return g};q.l.u=q.C;q.b("ko.dependentObservable",q.l);
(function(){function d(a,f,g){g=g||new c;a=f(a);if(!(typeof a=="object"&&a!==n&&a!==l))return a;var i=a instanceof Array?[]:{};g.save(a,i);e(a,function(c){var e=f(a[c]);switch(typeof e){case "boolean":case "number":case "string":case "function":i[c]=e;break;case "object":case "undefined":var k=g.get(e);i[c]=k!==l?k:d(e,f,g)}});return i}function e(a,f){if(a instanceof Array)for(var c=0;c<a.length;c++)f(c);else for(c in a)f(c)}function c(){var a=[],f=[];this.save=function(c,d){var e=q.a.h(a,c);e>=0?
f[e]=d:(a.push(c),f.push(d))};this.get=function(c){c=q.a.h(a,c);return c>=0?f[c]:l}}q.Ga=function(a){arguments.length==0&&b(Error("When calling ko.toJS, pass the object you want to convert."));return d(a,function(a){for(var c=0;q.M(a)&&c<10;c++)a=a();return a})};q.toJSON=function(a){a=q.Ga(a);return q.a.ja(a)}})();q.b("ko.toJS",q.Ga);q.b("ko.toJSON",q.toJSON);
q.g={q:function(d){return d.tagName=="OPTION"?d.__ko__hasDomDataOptionValue__===!0?q.a.e.get(d,q.c.options.fa):d.getAttribute("value"):d.tagName=="SELECT"?d.selectedIndex>=0?q.g.q(d.options[d.selectedIndex]):l:d.value},R:function(d,e){if(d.tagName=="OPTION")switch(typeof e){case "string":case "number":q.a.e.set(d,q.c.options.fa,l);"__ko__hasDomDataOptionValue__"in d&&delete d.__ko__hasDomDataOptionValue__;d.value=e;break;default:q.a.e.set(d,q.c.options.fa,e),d.__ko__hasDomDataOptionValue__=!0,d.value=
""}else if(d.tagName=="SELECT")for(var c=d.options.length-1;c>=0;c--){if(q.g.q(d.options[c])==e){d.selectedIndex=c;break}}else{if(e===n||e===l)e="";d.value=e}}};q.b("ko.selectExtensions",q.g);q.b("ko.selectExtensions.readValue",q.g.q);q.b("ko.selectExtensions.writeValue",q.g.R);
q.B=function(){function d(a,c){for(var d=n;a!=d;)d=a,a=a.replace(e,function(a,f){return c[f]});return a}var e=/\@ko_token_(\d+)\@/g,c=/^[\_$a-z][\_$a-z0-9]*(\[.*?\])*(\.[\_$a-z][\_$a-z0-9]*(\[.*?\])*)*$/i,a=["true","false"];return{za:function(a){var c=q.a.t(a);if(c.length<3)return[];c.charAt(0)==="{"&&(c=c.substring(1,c.length-1));for(var a=[],e=n,h,j=0;j<c.length;j++){var k=c.charAt(j);if(e===n)switch(k){case '"':case "'":case "/":e=j,h=k}else if(k==h&&c.charAt(j-1)!=="\\"){k=c.substring(e,j+1);
a.push(k);var m="@ko_token_"+(a.length-1)+"@",c=c.substring(0,e)+m+c.substring(j+1);j-=k.length-m.length;e=n}}h=e=n;for(var o=0,p=n,j=0;j<c.length;j++){k=c.charAt(j);if(e===n)switch(k){case "{":e=j;p=k;h="}";break;case "(":e=j;p=k;h=")";break;case "[":e=j,p=k,h="]"}k===p?o++:k===h&&(o--,o===0&&(k=c.substring(e,j+1),a.push(k),m="@ko_token_"+(a.length-1)+"@",c=c.substring(0,e)+m+c.substring(j+1),j-=k.length-m.length,e=n))}h=[];c=c.split(",");e=0;for(j=c.length;e<j;e++)o=c[e],p=o.indexOf(":"),p>0&&p<
o.length-1?(k=o.substring(p+1),h.push({key:d(o.substring(0,p),a),value:d(k,a)})):h.push({Ja:d(o,a)});return h},aa:function(f){for(var d=q.B.za(f),e=[],f=[],h,j=0;h=d[j];j++)if(e.length>0&&e.push(","),h.key){var k;a:{k=h.key;var m=q.a.t(k);switch(m.length&&m.charAt(0)){case "'":case '"':break a;default:k="'"+m+"'"}}e.push(k);e.push(":");e.push(h.value);m=q.a.t(h.value);if(q.a.h(a,q.a.t(m).toLowerCase())>=0?0:m.match(c)!==n)f.length>0&&f.push(", "),f.push(k+" : function(__ko_value) { "+h.value+" = __ko_value; }")}else h.Ja&&
e.push(h.Ja);d=e.join("");f.length>0&&(d=d+", '_ko_property_writers' : { "+f.join("")+" } ");return d}}}();q.b("ko.jsonExpressionRewriting",q.B);q.b("ko.jsonExpressionRewriting.parseObjectLiteral",q.B.za);q.b("ko.jsonExpressionRewriting.insertPropertyAccessorsIntoJson",q.B.aa);
(function(){function d(a){return a.nodeType==8&&a.nodeValue.match(c)}function e(c){for(var g=c,e=1,h=[];g=g.nextSibling;){if(g.nodeType==8&&g.nodeValue.match(a)&&(e--,e===0))return h;h.push(g);d(g)&&e++}b(Error("Cannot find closing comment tag to match: "+c.nodeValue))}var c=/^\s*ko\s+(.*\:.*)\s*$/,a=/^\s*\/ko\s*$/;q.k={childNodes:function(a){return d(a)?e(a):a.childNodes},$:function(a){if(d(a))for(var a=q.k.childNodes(a),c=0,e=a.length;c<e;c++)q.removeNode(a[c]);else q.a.I(a)},ha:function(a,c){if(d(a)){q.k.$(a);
for(var e=a.nextSibling,h=0,j=c.length;h<j;h++)e.parentNode.insertBefore(c[h],e)}else q.a.ha(a,c)},nb:function(a,c){d(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},cb:function(a,c,e){d(a)?a.parentNode.insertBefore(c,e.nextSibling):e.nextSibling?a.insertBefore(c,e.nextSibling):a.appendChild(c)},nextSibling:function(c){if(d(c))var g=e(c),c=(g.length>0?g[g.length-1].nextSibling:c.nextSibling).nextSibling;else c=c.nextSibling&&c.nextSibling.nodeType==
8&&c.nextSibling.nodeValue.match(a)?l:c.nextSibling;return c},ma:function(a){return(a=d(a))?a[1]:n},Za:function(a){if(q.k.ma(a)){var c;c=q.k.childNodes(a);for(var d=[],e=0,j=c.length;e<j;e++)d.push(q.a.outerHTML(c[e]));c=String.prototype.concat.apply("",d);q.k.$(a);(new q.i.w(a)).text(c)}}}})();
(function(){function d(a,f,g){var i=!0,h=f.nodeType==1;if(q.k.ma(f)||h&&g||h&&f.getAttribute(c))i=e(f,n,a,g).sb;if(h&&i)for(f=f.childNodes[0];f;)d(a,f,!1),f=q.k.nextSibling(f)}function e(a,f,d,e){function h(a){return function(){return o[a]}}function j(){return o}var k=!0,m=c;q.k.Za(a);var o,p;new q.l(function(){var c=d&&d instanceof q.z?d:new q.z(q.a.d(d)),v=c.$data;e&&q.Fa(a,c);var t=typeof f=="function"?f():f,u=a.nodeType==1&&a.getAttribute(m)||q.k.ma(a);if(t||u){if(!t)try{var w=" { "+q.B.aa(u)+
" } ",t=q.a.Ya(w,v===n?window:v,c)}catch(x){b(Error("Unable to parse binding attribute.\nMessage: "+x+";\nAttribute value: "+u))}o=t;if(k)for(var s in o)if(q.c[s]&&typeof q.c[s].init=="function"&&(u=(0,q.c[s].init)(a,h(s),j,v,c))&&u.controlsDescendantBindings)p!==l&&b(Error("Multiple bindings ("+p+" and "+s+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.")),p=s;for(s in o)q.c[s]&&typeof q.c[s].update=="function"&&(0,q.c[s].update)(a,
h(s),j,v,c)}},n,{disposeWhenNodeIsRemoved:a});k=!1;return{sb:p===l}}var c="data-bind";q.c={};q.z=function(a,c){this.$data=a;c?(this.$parent=c.$data,this.$parents=(c.$parents||[]).slice(0),this.$parents.unshift(this.$parent),this.$root=c.$root):(this.$parents=[],this.$root=a)};q.z.prototype={X:function(a){return new q.z(a,this)}};q.Fa=function(a,c){if(arguments.length==2)q.a.e.set(a,"__ko_bindingContext__",c);else return q.a.e.get(a,"__ko_bindingContext__")};q.qa=function(a,c,d){return e(a,c,d,!0)};
q.pa=function(a,c){c&&c.nodeType!==1&&c.nodeType!==8&&b(Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node"));c=c||window.document.body;d(a,c,!0)};q.W=function(a){var c=q.Fa(a);if(c)return c;if(a.parentNode)return q.W(a.parentNode)};q.Sa=function(a){return(a=q.W(a))?a.$data:l};q.b("ko.bindingHandlers",q.c);q.b("ko.applyBindings",q.pa);q.b("ko.applyBindingsToNode",q.qa);q.b("ko.contextFor",q.W);q.b("ko.dataFor",q.Sa)})();
q.a.o(["click"],function(d){q.c[d]={init:function(e,c,a,f){return q.c.event.init.call(this,e,function(){var a={};a[d]=c();return a},a,f)}}});q.c.event={init:function(d,e,c,a){var f=e()||{},g;for(g in f)(function(){var f=g;typeof f=="string"&&q.a.D(d,f,function(d){var g,k=e()[f],m=c();try{g=k.apply(a,arguments)}finally{if(g!==!0)d.preventDefault?d.preventDefault():d.returnValue=!1}if(m[f+"Bubble"]===!1)d.cancelBubble=!0,d.stopPropagation&&d.stopPropagation()})})()}};
q.c.submit={init:function(d,e,c,a){typeof e()!="function"&&b(Error("The value for a submit binding must be a function to invoke on submit"));q.a.D(d,"submit",function(c){var g,i=e();try{g=i.call(a,d)}finally{if(g!==!0)c.preventDefault?c.preventDefault():c.returnValue=!1}})}};q.c.visible={update:function(d,e){var c=q.a.d(e()),a=d.style.display!="none";if(c&&!a)d.style.display="";else if(!c&&a)d.style.display="none"}};
q.c.enable={update:function(d,e){var c=q.a.d(e());if(c&&d.disabled)d.removeAttribute("disabled");else if(!c&&!d.disabled)d.disabled=!0}};q.c.disable={update:function(d,e){q.c.enable.update(d,function(){return!q.a.d(e())})}};
q.c.value={init:function(d,e,c){var a=c().valueUpdate||"change",f=!1;q.a.tb(a,"after")&&(f=!0,a=a.substring(5));var g=f?function(a){setTimeout(a,0)}:function(a){a()};q.a.D(d,a,function(){g(function(){var a=e(),f=q.g.q(d);q.N(a)?a(f):(a=c(),a._ko_property_writers&&a._ko_property_writers.value&&a._ko_property_writers.value(f))})})},update:function(d,e){var c=q.a.d(e()),a=q.g.q(d),f=c!=a;c===0&&a!==0&&a!=="0"&&(f=!0);f&&(a=function(){q.g.R(d,c)},a(),d.tagName=="SELECT"&&setTimeout(a,0));d.tagName=="SELECT"&&
(a=q.g.q(d),a!==c&&q.a.Ia(d,"change"))}};
q.c.options={update:function(d,e,c){d.tagName!="SELECT"&&b(Error("options binding applies only to SELECT elements"));var a=q.a.T(q.a.S(d.childNodes,function(a){return a.tagName&&a.tagName=="OPTION"&&a.selected}),function(a){return q.g.q(a)||a.innerText||a.textContent}),f=d.scrollTop,g=q.a.d(e());q.a.I(d);if(g){var i=c();typeof g.length!="number"&&(g=[g]);if(i.optionsCaption){var h=document.createElement("OPTION");h.innerHTML=i.optionsCaption;q.g.R(h,l);d.appendChild(h)}c=0;for(e=g.length;c<e;c++){var h=
document.createElement("OPTION"),j=typeof i.optionsValue=="string"?g[c][i.optionsValue]:g[c],k=i.optionsText;optionText=typeof k=="function"?k(g[c]):typeof k=="string"?g[c][k]:j;j=q.a.d(j);optionText=q.a.d(optionText);q.g.R(h,j);h.innerHTML=optionText.toString();d.appendChild(h)}g=d.getElementsByTagName("OPTION");c=i=0;for(e=g.length;c<e;c++)q.a.h(a,q.g.q(g[c]))>=0&&(q.a.Ea(g[c],!0),i++);if(f)d.scrollTop=f}}};q.c.options.fa="__ko.bindingHandlers.options.optionValueDomData__";
q.c.selectedOptions={va:function(d){for(var e=[],d=d.childNodes,c=0,a=d.length;c<a;c++){var f=d[c];f.tagName=="OPTION"&&f.selected&&e.push(q.g.q(f))}return e},init:function(d,e,c){q.a.D(d,"change",function(){var a=e();q.N(a)?a(q.c.selectedOptions.va(this)):(a=c(),a._ko_property_writers&&a._ko_property_writers.value&&a._ko_property_writers.value(q.c.selectedOptions.va(this)))})},update:function(d,e){d.tagName!="SELECT"&&b(Error("values binding applies only to SELECT elements"));var c=q.a.d(e());if(c&&
typeof c.length=="number")for(var a=d.childNodes,f=0,g=a.length;f<g;f++){var i=a[f];i.tagName=="OPTION"&&q.a.Ea(i,q.a.h(c,q.g.q(i))>=0)}}};q.c.text={update:function(d,e){var c=q.a.d(e());if(c===n||c===l)c="";typeof d.innerText=="string"?d.innerText=c:d.textContent=c}};q.c.html={init:function(){return{controlsDescendantBindings:!0}},update:function(d,e){var c=q.a.d(e());q.a.rb(d,c)}};
q.c.css={update:function(d,e){var c=q.a.d(e()||{}),a;for(a in c)if(typeof a=="string"){var f=q.a.d(c[a]);q.a.Ha(d,a,f)}}};q.c.style={update:function(d,e){var c=q.a.d(e()||{}),a;for(a in c)if(typeof a=="string"){var f=q.a.d(c[a]);d.style[a]=f||""}}};q.c.uniqueName={init:function(d,e){if(e())d.name="ko_unique_"+ ++q.c.uniqueName.Ra,q.a.ba&&d.mergeAttributes(document.createElement("<input name='"+d.name+"'/>"),!1)}};q.c.uniqueName.Ra=0;
q.c.checked={init:function(d,e,c){q.a.D(d,"click",function(){var a;if(d.type=="checkbox")a=d.checked;else if(d.type=="radio"&&d.checked)a=d.value;else return;var f=e();d.type=="checkbox"&&q.a.d(f)instanceof Array?(a=q.a.h(q.a.d(f),d.value),d.checked&&a<0?f.push(d.value):!d.checked&&a>=0&&f.splice(a,1)):q.N(f)?f()!==a&&f(a):(f=c(),f._ko_property_writers&&f._ko_property_writers.checked&&f._ko_property_writers.checked(a))});d.type=="radio"&&!d.name&&q.c.uniqueName.init(d,function(){return!0})},update:function(d,
e){var c=q.a.d(e());if(d.type=="checkbox")d.checked=c instanceof Array?q.a.h(c,d.value)>=0:c,c&&q.a.ba&&d.mergeAttributes(document.createElement("<input type='checkbox' checked='checked' />"),!1);else if(d.type=="radio")d.checked=d.value==c,d.value==c&&(q.a.ba||q.a.fb)&&d.mergeAttributes(document.createElement("<input type='radio' checked='checked' />"),!1)}};
q.c.attr={update:function(d,e){var c=q.a.d(e())||{},a;for(a in c)if(typeof a=="string"){var f=q.a.d(c[a]);f===!1||f===n||f===l?d.removeAttribute(a):d.setAttribute(a,f.toString())}}};q.c["with"]={m:function(d){return function(){var e=d();return{"if":e,data:e,templateEngine:q.n.A}}},init:function(d,e){return q.c.template.init(d,q.c["with"].m(e))},update:function(d,e,c,a,f){return q.c.template.update(d,q.c["with"].m(e),c,a,f)}};
q.c["if"]={m:function(d){return function(){return{"if":d(),templateEngine:q.n.A}}},init:function(d,e){return q.c.template.init(d,q.c["if"].m(e))},update:function(d,e,c,a,f){return q.c.template.update(d,q.c["if"].m(e),c,a,f)}};q.c.ifnot={m:function(d){return function(){return{ifnot:d(),templateEngine:q.n.A}}},init:function(d,e){return q.c.template.init(d,q.c.ifnot.m(e))},update:function(d,e,c,a,f){return q.c.template.update(d,q.c.ifnot.m(e),c,a,f)}};
q.c.foreach={m:function(d){return function(){var e=q.a.d(d());return!e||typeof e.length=="number"?{foreach:e,templateEngine:q.n.A}:{foreach:e.data,includeDestroyed:e.includeDestroyed,afterAdd:e.afterAdd,beforeRemove:e.beforeRemove,afterRender:e.afterRender,templateEngine:q.n.A}}},init:function(d,e){return q.c.template.init(d,q.c.foreach.m(e))},update:function(d,e,c,a,f){return q.c.template.update(d,q.c.foreach.m(e),c,a,f)}};q.r=function(){};q.r.prototype.renderTemplateSource=function(){b("Override renderTemplateSource in your ko.templateEngine subclass")};
q.r.prototype.createJavaScriptEvaluatorBlock=function(){b("Override createJavaScriptEvaluatorBlock in your ko.templateEngine subclass")};q.r.prototype.makeTemplateSource=function(d){if(typeof d=="string"){var e=document.getElementById(d);e||b(Error("Cannot find template with ID "+d));return new q.i.f(e)}else if(d.nodeType==1||d.nodeType==8)return new q.i.w(d);else b(Error("Unrecognised template type: "+d))};
q.r.prototype.renderTemplate=function(d,e,c){return this.renderTemplateSource(this.makeTemplateSource(d),e,c)};q.r.prototype.isTemplateRewritten=function(d){return this.allowTemplateRewriting===!1?!0:this.O&&this.O[d]?!0:this.makeTemplateSource(d).data("isRewritten")};q.r.prototype.rewriteTemplate=function(d,e){var c=this.makeTemplateSource(d),a=e(c.text());c.text(a);c.data("isRewritten",!0);if(typeof d=="string")this.O=this.O||{},this.O[d]=!0};q.b("ko.templateEngine",q.r);
q.P=function(){var d=/(<[a-z]+\d*(\s+(?!data-bind=)[a-z0-9\-]+(=(\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind=(["'])([\s\S]*?)\5/gi;return{Xa:function(d,c){c.isTemplateRewritten(d)||c.rewriteTemplate(d,function(a){return q.P.jb(a,c)})},jb:function(e,c){return e.replace(d,function(a,d,e,i,h,j,k){a=q.B.aa(k);return c.createJavaScriptEvaluatorBlock("ko.templateRewriting.applyMemoizedBindingsToNextSibling(function() {                     return (function() { return { "+a+" } })()                 })")+d})},
Ma:function(d){return q.p.ea(function(c,a){c.nextSibling&&q.qa(c.nextSibling,d,a)})}}}();q.b("ko.templateRewriting",q.P);q.b("ko.templateRewriting.applyMemoizedBindingsToNextSibling",q.P.Ma);
(function(){q.i={};q.i.f=function(d){this.f=d};q.i.f.prototype.text=function(){if(arguments.length==0)return this.f.tagName.toLowerCase()=="script"?this.f.text:this.f.innerHTML;else{var d=arguments[0];this.f.tagName.toLowerCase()=="script"?this.f.text=d:this.f.innerHTML=d}};q.i.f.prototype.data=function(d){if(arguments.length===1)return q.a.e.get(this.f,"templateSourceData_"+d);else q.a.e.set(this.f,"templateSourceData_"+d,arguments[0])};q.i.w=function(d){this.f=d};q.i.w.prototype=new q.i.f;q.i.w.prototype.text=
function(){if(arguments.length==0)return q.a.e.get(this.f,"__ko_anon_template__");else q.a.e.set(this.f,"__ko_anon_template__",arguments[0])};q.b("ko.templateSources",q.i);q.b("ko.templateSources.domElement",q.i.f);q.b("ko.templateSources.anonymousTemplate",q.i.w)})();
(function(){function d(c,a,d,g,i){var i=i||{},h=i.templateEngine||e;q.P.Xa(d,h);d=h.renderTemplate(d,g,i);(typeof d.length!="number"||d.length>0&&typeof d[0].nodeType!="number")&&b("Template engine must return an array of DOM nodes");h=!1;switch(a){case "replaceChildren":q.k.ha(c,d);h=!0;break;case "replaceNode":q.a.Ca(c,d);h=!0;break;case "ignoreTargetNode":break;default:b(Error("Unknown renderMode: "+a))}h&&(q.na(d,g),i.afterRender&&i.afterRender(d,g.$data));return d}var e;q.ia=function(c){c!=l&&
!(c instanceof q.r)&&b("templateEngine must inherit from ko.templateEngine");e=c};q.na=function(c,a){for(var d=q.a.F([],c),e,i=c.length>0?c[0].parentNode:n,h=0;e=d[h];h++)if(e.parentNode===i)switch(e.nodeType){case 1:case 8:q.pa(a,e),q.p.La(e,[a])}};q.ga=function(c,a,f,g,i){f=f||{};(f.templateEngine||e)==l&&b("Set a template engine before calling renderTemplate");i=i||"replaceChildren";if(g){var h=g.nodeType?g:g.length>0?g[0]:n;return new q.l(function(){var e=a&&a instanceof q.z?a:new q.z(q.a.d(a)),
k=typeof c=="function"?c(e.$data):c,e=d(g,i,k,e,f);i=="replaceNode"&&(g=e,h=g.nodeType?g:g.length>0?g[0]:n)},n,{disposeWhen:function(){return!h||!q.a.Z(h)},disposeWhenNodeIsRemoved:h&&i=="replaceNode"?h.parentNode:h})}else return q.p.ea(function(d){q.ga(c,a,f,d,"replaceNode")})};q.qb=function(c,a,e,g,i){function h(a,c){var d=i.X(q.a.d(a));q.na(c,d);e.afterRender&&e.afterRender(c,d.$data)}return new q.l(function(){var j=q.a.d(a)||[];typeof j.length=="undefined"&&(j=[j]);j=q.a.S(j,function(a){return e.includeDestroyed||
!a._destroy});q.a.Da(g,j,function(a){var g=typeof c=="function"?c(a):c;return d(n,"ignoreTargetNode",g,i.X(q.a.d(a)),e)},e,h)},n,{disposeWhenNodeIsRemoved:g})};q.c.template={init:function(c,a){var d=q.a.d(a());typeof d!="string"&&!d.name&&c.nodeType==1&&((new q.i.w(c)).text(c.innerHTML),q.a.I(c));return{controlsDescendantBindings:!0}},update:function(c,a,d,e,i){a=q.a.d(a());e=!0;typeof a=="string"?d=a:(d=a.name,"if"in a&&(e=e&&q.a.d(a["if"])),"ifnot"in a&&(e=e&&!q.a.d(a.ifnot)));var h=n;typeof a.foreach!=
"undefined"?h=q.qb(d||c,e&&a.foreach||[],a,c,i):e?(i=typeof a=="object"&&"data"in a?i.X(q.a.d(a.data)):i,h=q.ga(d||c,i,a,c)):q.k.$(c);i=h;(a=q.a.e.get(c,"__ko__templateSubscriptionDomDataKey__"))&&typeof a.s=="function"&&a.s();q.a.e.set(c,"__ko__templateSubscriptionDomDataKey__",i)}}})();q.b("ko.setTemplateEngine",q.ia);q.b("ko.renderTemplate",q.ga);
q.a.H=function(d,e,c){if(c===l)return q.a.H(d,e,1)||q.a.H(d,e,10)||q.a.H(d,e,Number.MAX_VALUE);else{for(var d=d||[],e=e||[],a=d,f=e,g=[],i=0;i<=f.length;i++)g[i]=[];for(var i=0,h=Math.min(a.length,c);i<=h;i++)g[0][i]=i;i=1;for(h=Math.min(f.length,c);i<=h;i++)g[i][0]=i;for(var h=a.length,j,k=f.length,i=1;i<=h;i++){j=Math.max(1,i-c);for(var m=Math.min(k,i+c);j<=m;j++)g[j][i]=a[i-1]===f[j-1]?g[j-1][i-1]:Math.min(g[j-1][i]===l?Number.MAX_VALUE:g[j-1][i]+1,g[j][i-1]===l?Number.MAX_VALUE:g[j][i-1]+1)}c=
d.length;a=e.length;f=[];i=g[a][c];if(i===l)g=n;else{for(;c>0||a>0;){h=g[a][c];k=a>0?g[a-1][c]:i+1;m=c>0?g[a][c-1]:i+1;j=a>0&&c>0?g[a-1][c-1]:i+1;if(k===l||k<h-1)k=i+1;if(m===l||m<h-1)m=i+1;j<h-1&&(j=i+1);k<=m&&k<j?(f.push({status:"added",value:e[a-1]}),a--):(m<k&&m<j?f.push({status:"deleted",value:d[c-1]}):(f.push({status:"retained",value:d[c-1]}),a--),c--)}g=f.reverse()}return g}};q.b("ko.utils.compareArrays",q.a.H);
(function(){function d(d,c,a,f){var g=[],d=q.l(function(){var d=c(a)||[];g.length>0&&(q.a.Ca(g,d),f&&f(a,d));g.splice(0,g.length);q.a.F(g,d)},n,{disposeWhenNodeIsRemoved:d,disposeWhen:function(){return g.length==0||!q.a.Z(g[0])}});return{hb:g,l:d}}q.a.Da=function(e,c,a,f,g){for(var c=c||[],f=f||{},i=q.a.e.get(e,"setDomNodeChildrenFromArrayMapping_lastMappingResult")===l,h=q.a.e.get(e,"setDomNodeChildrenFromArrayMapping_lastMappingResult")||[],j=q.a.T(h,function(a){return a.Na}),k=q.a.H(j,c),c=[],
m=0,o=[],j=[],p=n,r=0,v=k.length;r<v;r++)switch(k[r].status){case "retained":var t=h[m];c.push(t);t.L.length>0&&(p=t.L[t.L.length-1]);m++;break;case "deleted":h[m].l.s();q.a.o(h[m].L,function(a){o.push({element:a,index:r,value:k[r].value});p=a});m++;break;case "added":var t=k[r].value,u=d(e,a,t,g),w=u.hb;c.push({Na:k[r].value,L:w,l:u.l});for(var u=0,x=w.length;u<x;u++){var s=w[u];j.push({element:s,index:r,value:k[r].value});p==n?q.k.nb(e,s):q.k.cb(e,s,p);p=s}g&&g(t,w)}q.a.o(o,function(a){q.G(a.element)});
a=!1;if(!i){if(f.afterAdd)for(r=0;r<j.length;r++)f.afterAdd(j[r].element,j[r].index,j[r].value);if(f.beforeRemove){for(r=0;r<o.length;r++)f.beforeRemove(o[r].element,o[r].index,o[r].value);a=!0}}a||q.a.o(o,function(a){q.removeNode(a.element)});q.a.e.set(e,"setDomNodeChildrenFromArrayMapping_lastMappingResult",c)}})();q.b("ko.utils.setDomNodeChildrenFromArrayMapping",q.a.Da);q.n=function(){this.allowTemplateRewriting=!1};q.n.prototype=new q.r;
q.n.prototype.renderTemplateSource=function(d){d=d.text();return q.a.xa(d)};q.n.A=new q.n;q.ia(q.n.A);q.b("ko.nativeTemplateEngine",q.n);
(function(){q.ca=function(){var d=this.gb=function(){if(typeof jQuery=="undefined"||!jQuery.tmpl)return 0;try{if(jQuery.tmpl.tag.tmpl.open.toString().indexOf("__")>=0)return 2}catch(c){}return 1}();this.renderTemplateSource=function(c,a,f){var f=f||{},g=d==0?"jquery.tmpl not detected.\nTo use KO's default template engine, reference jQuery and jquery.tmpl. See Knockout installation documentation for more details.":d==1?"Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.":
n;g&&b(Error(g));g=c.data("precompiled");g||(g=c.text()||"",g=jQuery.template(n,"{{ko_with $item.koBindingContext}}"+g+"{{/ko_with}}"),c.data("precompiled",g));c=[a.$data];a=jQuery.extend({koBindingContext:a},f.templateOptions);a=jQuery.tmpl(g,c,a);a.appendTo(document.createElement("div"));jQuery.fragments={};return a};this.createJavaScriptEvaluatorBlock=function(c){return"{{ko_code ((function() { return "+c+" })()) }}"};this.addTemplate=function(c,a){document.write("<script type='text/html' id='"+
c+"'>"+a+"<\/script>")};if(d>=2)jQuery.tmpl.tag.ko_code={open:"__.push($1 || '');"},jQuery.tmpl.tag.ko_with={open:"with($1) {",close:"} "}};q.ca.prototype=new q.r;var d=new q.ca;d.gb>0&&q.ia(d);q.b("ko.jqueryTmplTemplateEngine",q.ca)})();
})(window);                  
