//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Indexing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.Indexing.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;xaml&quot;: [
        ///    &quot;xaml&quot;
        ///  ],
        ///
        ///  &quot;mvc&quot;: [
        ///    &quot;mvc&quot;
        ///  ],
        ///
        ///  &quot;wpf&quot;: [
        ///    &quot;wpf&quot;
        ///  ],
        ///
        ///  &quot;ef&quot;: [
        ///    &quot;ef&quot;,
        ///    &quot;entity framework&quot;
        ///  ],
        ///
        ///  &quot;uwp&quot;: [
        ///    &quot;uwp&quot;,
        ///    &quot;universal windows platform&quot;
        ///  ],
        ///
        ///  &quot;markdown&quot;: [
        ///    &quot;markdown&quot;
        ///  ],
        ///
        ///  &quot;http&quot;: [
        ///    &quot;http&quot;
        ///  ],
        ///
        ///  &quot;https&quot;: [
        ///    &quot;https&quot;
        ///  ],
        ///
        ///  &quot;ftp&quot;: [
        ///    &quot;ftp&quot;
        ///  ]
        ///}.
        /// </summary>
        internal static string NuGetAcronymExpansions {
            get {
                return ResourceManager.GetString("NuGetAcronymExpansions", resourceCulture);
            }
        }
    }
}
