#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    using NuGetGallery;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Error.cshtml")]
    public class Error : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Error()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\Error.cshtml"
  
    Layout = "~/Errors/ErrorLayout.cshtml";
    Page.Title = "Error";


            
            #line default
            #line hidden
WriteLiteral(@"
    <h2>
        Sorry, an error occurred while processing your request.
    </h2>

    <div class=""error-page"">
        <h1>Error: Oh no, we broke something!</h1>
        <p>You might be here because:</p>
        <ul>
            <li>There is an error on our server and the server is &quot;given her all she's got, captain.&quot; </li>
            <li>The system is down, the system is down, the system is down.</li>
            <li>Our name is smalls.</li>
        </ul>

        <p>
            We have logged the error and we will look into it, and make sure it doesn’t happen again. However if you keep 
            seeing this page please File a bug in <a href=""https://github.com/NuGet/NuGetGallery/issues"">the NuGet Gallery issue tracker</a>.
        </p>

        <h2 class=""search"">Search For Something Else</h2>
        <form action="""" onsubmit=""return submitQuery()"">
            <input name=""q"" id=""searchBoxInput"" placeholder=""Search Gallery"" />
            <input id=""searchBoxSubmit"" type=""submit"" value="" "" />
        </form>

    </div>

    <script type=""text/javascript"">
        function submitQuery() {
            window.location =  """);


            
            #line 34 "..\..\Views\Shared\Error.cshtml"
                           Write(Href("~/packages"));

            
            #line default
            #line hidden
WriteLiteral("?q=\" \r\n            + encodeURIComponent($(\"#searchBoxInput\").val());\r\n           " +
" return false;\r\n        }\r\n    </script>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
