#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery.Views.Shared
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/TwoColumnLayout.cshtml")]
    public class TwoColumnLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public TwoColumnLayout()
        {
        }
        public override void Execute()
        {


#line 1 "..\..\Views\Shared\TwoColumnLayout.cshtml"

            Layout = "Layout.cshtml";



#line default
#line hidden
            WriteLiteral("<div id=\"layout-main\" class=\"aside-1 group\">  \r\n    <aside id=\"aside-first\" class" +
            "=\"aside-first group\">\r\n        <div class=\"zone zone-aside-first\">\r\n            " +
            "<nav id=\"leftNav\">\r\n                ");



#line 8 "..\..\Views\Shared\TwoColumnLayout.cshtml"
            Write(RenderSection("LeftNav"));


#line default
#line hidden
            WriteLiteral(@"
            </nav>
        </div>
    </aside>
    
    <div id=""layout-content"" class=""group"">
        <div id=""content"" class=""group"">
            <div class=""zone zone-content"">
                <section>
                    <header>
                        ");



#line 18 "..\..\Views\Shared\TwoColumnLayout.cshtml"
            Write(RenderSection("ContentHeader"));


#line default
#line hidden
            WriteLiteral("\r\n                    </header>\r\n                    ");



#line 20 "..\..\Views\Shared\TwoColumnLayout.cshtml"
            Write(RenderBody());


#line default
#line hidden
            WriteLiteral("\r\n                </section>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</d" +
            "iv>\r\n\r\n");



#line 27 "..\..\Views\Shared\TwoColumnLayout.cshtml"
            Write(RenderSection("BottomScripts", required: false));


#line default
#line hidden
            WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
