<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
    <Description>Promotion processing for validated staged packages.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NuGet.Services.Staging\NuGet.Services.Staging.csproj" />
    <ProjectReference Include="..\Validation.Common.Job\Validation.Common.Job.csproj" />
    <ProjectReference Include="..\NuGetGallery.Core\NuGetGallery.Core.csproj" />
  </ItemGroup>
</Project>
