PREFIX nuget: <http://schema.nuget.org/schema#>
PREFIX catalog: <http://schema.nuget.org/catalog#>

CONSTRUCT
{
    ?package a nuget:Package ;
	         nuget:registration ?registration ;
             nuget:packageContent ?packageContent ;
	         nuget:catalogEntry ?catalogPackage .

    ?catalogPackage a nuget:PackageDetails ;
                    nuget:id ?id ;
                    nuget:version ?version ;
                    nuget:dependencyGroup ?dependency_group ;
	                nuget:published ?published .

    ?dependency_group a nuget:PackageDependencyGroup ;
	                  nuget:dependency ?dependency ;
                      nuget:targetFramework ?dependency_group_targetFramework .

    ?dependency a nuget:PackageDependency ;
	            nuget:id ?dependency_id ;
                nuget:registration ?dependency_registration ;
                nuget:range ?dependency_version .
}
WHERE
{
	BIND (@catalogPackage AS ?catalogPackage)
	BIND (@package AS ?package)

	BIND (IRI(CONCAT(STR(@baseAddress), "index.json")) AS ?registration)

    ?catalogPackage nuget:version ?version ;
                    nuget:id ?id ;
	                nuget:published ?published ;
					nuget:packageContent ?packageContent .

    OPTIONAL
    {
        ?catalogPackage nuget:dependencyGroup ?dependency_group .

        OPTIONAL { ?dependency_group nuget:targetFramework ?dependency_group_targetFramework . }

		OPTIONAL
		{
			?dependency_group nuget:dependency ?dependency .
			?dependency nuget:id ?dependency_id .
			BIND (IRI(CONCAT(STR(@registrationBaseAddress), LCASE(?dependency_id), "/index.json")) AS ?dependency_registration)
        
	        OPTIONAL { ?dependency nuget:range ?dependency_version . }
		}
    }
}
