PREFIX nuget: <http://nuget.org/schema#>

CONSTRUCT
{
    @resource a nuget:Container ;
	          nuget:item ?item ;
	          nuget:container ?container .

	?item nuget:published ?latest .
}
WHERE
{
    @resource a nuget:Container ;
              nuget:item ?item .

	OPTIONAL { @resource nuget:container ?container . }

	{
		SELECT ?item MAX(?published) AS ?latest
		WHERE
		{
			@resource nuget:item ?item .
			?item nuget:item*/nuget:published ?published .
		}
		GROUP BY ?item
	}
}
