PREFIX nuget: <http://schema.nuget.org/>

CONSTRUCT
{
       ?s ?p ?o .
}
WHERE
{
    ?s ?p ?o .

    MINUS
    {
        ?s a nuget:PackageRegistration ; 
           nuget:package ?o .
        ?o nuget:version @version .
    }
}
