PREFIX nuget: <http://schema.nuget.org/schema#> 

SELECT ?targetFramework ?id ?range
WHERE
{
	@package nuget:dependencyGroup ?dependencyGroup .

	OPTIONAL { ?dependencyGroup nuget:targetFramework ?tf . }
	OPTIONAL
	{
		?dependencyGroup nuget:dependency ?dependency .
		?dependency nuget:id ?id ;
		            nuget:range ?range .
	}

	BIND (IF(BOUND(?tf), ?tf, "") AS ?targetFramework)
}
