PREFIX nuget: <http://schema.nuget.org/schema#> 

SELECT DISTINCT ?versionRange
WHERE
{
    BIND (@resourceUri AS ?resourceUri)

	?resourceUri     nuget:dependencyGroup ?dependencyGroup             .
	?dependencyGroup a                     nuget:PackageDependencyGroup .
	?dependencyGroup nuget:dependency      ?dependency                  .
	?dependency      a                     nuget:PackageDependency      .
	?dependency      nuget:range           ?versionRange                .
}
