PREFIX nuget: <http://schema.nuget.org/schema#> 
PREFIX gallery: <http://schema.nuget.org/gallery#> 

SELECT ?key ?checksum
WHERE
{
	?package a nuget:Package ;
	         gallery:key ?key ;
	         gallery:checksum ?checksum .
}
