PREFIX nuget: <http://schema.nuget.org/> 
PREFIX gallery: <http://schema.nuget.org/> 

SELECT ?key ?checksum
WHERE
{
	?package a nuget:Package ;
	         gallery:key ?key ;
	         gallery:checksum ?checksum .
}
