PREFIX nuget: <http://schema.nuget.org/schema#> 

SELECT ?targetFramework ?assembly
WHERE
{
	@package nuget:frameworkAssemblyGroup ?frameworkAssemblyGroup .

	OPTIONAL { ?frameworkAssemblyGroup nuget:targetFramework ?tf . }
	OPTIONAL { ?frameworkAssemblyGroup nuget:assembly ?assembly . }

	BIND (IF(BOUND(?tf), ?tf, "") AS ?targetFramework)
}
