PREFIX nuget: <http://schema.nuget.org/schema#> 

SELECT ?id ?version
WHERE
{
	?package a nuget:DeletePackage ;
	         nuget:packageId ?s ;
	         nuget:version ?t .

	BIND (LCASE(?s) AS ?id)
	BIND (LCASE(?t) AS ?version)
}
