
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT
{
  ?subject a ?type .
}
WHERE
{
  ?type a owl:Restriction .
  ?type owl:onProperty ?predicate .
  ?type owl:minCardinality ?minCardinality .
  FILTER (?cardinality >= ?minCardinality)
  {
    SELECT ?subject ?predicate COUNT(?object) AS ?cardinality
    WHERE
    {
      ?subject ?predicate ?object .

      SELECT DISTINCT ?predicate
      WHERE
      {
        ?type a owl:Restriction .
        ?type owl:onProperty ?predicate .
        ?type owl:minCardinality ?minCardinality .
      }
    }
    GROUP BY ?subject ?predicate
  }
}
