
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT
{
	owl:equivalentClass rdfs:subPropertyOf rdfs:subClassOf.
	owl:equivalentProperty rdfs:subPropertyOf rdfs:subPropertyOf.
	owl:equivalentClass rdf:type owl:SymmetricProperty.
	owl:equivalentProperty rdf:type owl:SymmetricProperty.
	owl:inverseOf rdf:type owl:SymmetricProperty.
}
WHERE { ?s ?o ?p }