
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT
{
	?s rdf:type ?r
}
WHERE
{
	?r rdf:type owl:Restriction ; 
	   owl:onProperty ?p ;
	   owl:someValuesFrom ?c .
    
	?o rdf:type ?c. 
	?s ?p ?o
}
