#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetGallery
{
    using System;
    
    #line 4 "..\..\Views\Helpers\ViewHelpers.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    
    #line 3 "..\..\Views\Helpers\ViewHelpers.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Microsoft.Web.Helpers;
    
    #line 5 "..\..\Views\Helpers\ViewHelpers.cshtml"
    using NuGetGallery;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    public static class ViewHelpers
    {

public static System.Web.WebPages.HelperResult PreviousNextPager(IPreviousNextPager pager) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 7 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                                     
    if (pager.HasNextPage || pager.HasPreviousPage) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <ul class=\"pager\">\r\n            <li class=\"previous\">\r\n");



#line 11 "..\..\Views\Helpers\ViewHelpers.cshtml"
                 if (pager.HasPreviousPage) { 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <a href=\"");



#line 12 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, pager.PreviousPageUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" title=\"Go to the previous page.\">Previous</a>\r\n");



#line 13 "..\..\Views\Helpers\ViewHelpers.cshtml"
                }
                else {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "Previous");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 16 "..\..\Views\Helpers\ViewHelpers.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </li>\r\n            <li class=\"next\">\r\n");



#line 19 "..\..\Views\Helpers\ViewHelpers.cshtml"
                 if (pager.HasNextPage) { 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    <a href=\"");



#line 20 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, pager.NextPageUrl);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" title=\"Go to the next page.\">Next</a>\r\n");



#line 21 "..\..\Views\Helpers\ViewHelpers.cshtml"
                }
                else {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "Next");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 24 "..\..\Views\Helpers\ViewHelpers.cshtml"
                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </li>\r\n        </ul>\r\n");



#line 27 "..\..\Views\Helpers\ViewHelpers.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Option(string value, string label, string currentValue) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 30 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                                                 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <option value=\"");



#line 31 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, value);

#line default
#line hidden



#line 31 "..\..\Views\Helpers\ViewHelpers.cshtml"
                         WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");

#line default
#line hidden


#line 31 "..\..\Views\Helpers\ViewHelpers.cshtml"
                            if (value == currentValue) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "selected=\"selected\"");



#line 31 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                                                                        }
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">");



#line 31 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                               WebViewPage.WriteTo(@__razor_helper_writer, label);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</option>    \r\n");



#line 32 "..\..\Views\Helpers\ViewHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult UploadSequence(int currentStep) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 34 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ol class=\"sequence\">\r\n        ");



#line 36 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, SequenceStep(1, "Upload", currentStep));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        ");



#line 37 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, SequenceStep(2, "Verify Details", currentStep));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        ");



#line 38 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, SequenceStep(3, "Enjoy", currentStep));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    </ol>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"clear-fix\"><!--Sad Panda--></div>\r\n");



#line 41 "..\..\Views\Helpers\ViewHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult SequenceStep(int step, string caption, int currentStep) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 43 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                                                 
    if (currentStep > step) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li class=\"past\">");



#line 45 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, caption);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 46 "..\..\Views\Helpers\ViewHelpers.cshtml"
    }
    else if (currentStep == step) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li class=\"current\">");



#line 48 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, caption);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 49 "..\..\Views\Helpers\ViewHelpers.cshtml"
    }
    else {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li>");



#line 51 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, caption);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 52 "..\..\Views\Helpers\ViewHelpers.cshtml"
    }    

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult OwnersGravatar(IEnumerable<User> owners, int size, UrlHelper url, bool showName = true) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 55 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                                                                                 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul class=\"owners\">\r\n");



#line 57 "..\..\Views\Helpers\ViewHelpers.cshtml"
     foreach (var owner in owners) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li>\r\n            ");



#line 59 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, ViewHelpers.OwnerGravatar(owner, size, url, showName));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n        </li>\r\n");



#line 61 "..\..\Views\Helpers\ViewHelpers.cshtml"
    }  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ul>  \r\n");



#line 63 "..\..\Views\Helpers\ViewHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult OwnerGravatar(User owner, int size, UrlHelper url, bool showName = true) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 65 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <a class=\"owner\" href=\"");



#line 66 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, url.Action(MVC.Users.Profiles(owner.Username)));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" title=\"");



#line 66 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                        WebViewPage.WriteTo(@__razor_helper_writer, owner.Username);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        ");



#line 67 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GravatarImage(owner.EmailAddress, owner.Username, size));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 68 "..\..\Views\Helpers\ViewHelpers.cshtml"
         if (showName) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");



#line 69 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, owner.Username);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 70 "..\..\Views\Helpers\ViewHelpers.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </a>\r\n");



#line 72 "..\..\Views\Helpers\ViewHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult GravatarImage(string email, string username, int size) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 74 "..\..\Views\Helpers\ViewHelpers.cshtml"
                                                                

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    ");



#line 76 "..\..\Views\Helpers\ViewHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Gravatar.GetHtml(email, size, "retro", GravatarRating.G, attributes: new { width = size, height = size, title = username, @class = "owner-image" }));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 78 "..\..\Views\Helpers\ViewHelpers.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
