name: Gallery release trigger $(Build.BuildId) - $(Date:yyyyMMdd)

trigger:
  branches:
    include:
    - main
    - dev

pr: none

variables:
- name: NugetMultifeedWarnLevel
  value: none
  
pool:
  vmImage: 'windows-latest'

steps:
- powershell: |-
    $body = @{
      "templateParameters":
      {
        "NuGetGallerySubmoduleBranch": "$(Build.SourceBranchName)"
      }
    }
    $headers = @{ "Authorization" = "Bearer $env:ACCESS_TOKEN" };
    $url = "$(System.CollectionUri)$(System.TeamProject)/_apis/pipelines/21120/runs?api-version=7.0"
    Invoke-RestMethod -Uri $url -Method POST -Headers $headers -Body ($body | ConvertTo-Json) -ContentType "application/json"
  env:
    ACCESS_TOKEN: $(System.AccessToken)
