name: Gallery release trigger $(Build.BuildId) - $(Date:yyyyMMdd)

trigger:
  branches:
    include:
    - main
    - dev
    - agr-*

variables:
- name: NugetMultifeedWarnLevel
  value: none
  
pool:
  vmImage: 'windows-latest'

steps:
- powershell: Write-Host "Release trigger fired"
