name: Gallery release trigger $(Build.BuildId) - $(Date:yyyyMMdd)

trigger:
  branches:
    include:
    - japarson/ci-trigger

pr: none

variables:
- name: NugetMultifeedWarnLevel
  value: none

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    Write-Host "Hello World from the Gallery release trigger pipeline!"
  displayName: 'Hello World'
