name: Gallery release trigger $(Build.BuildId) - $(Date:yyyyMMdd)

trigger:
  branches:
    include:
    - main
    - dev
    - japarson/fix-trigger

pr: none

parameters:
- name: TargetPipelines
  type: object
  default:
  - id: 21120 # gallery web app
    name: Gallery Web App
  - id: 21280 # gallery packages
    name: Gallery Packages
  - id: 21128 # jobs
    name: Jobs
  - id: 21269 # common
    name: Common

variables:
- name: NugetMultifeedWarnLevel
  value: none
- name: TargetRef
  value: refs/heads/$(Build.SourceBranch)

pool:
  vmImage: 'windows-latest'

stages:
- stage: Trigger
  displayName: "Trigger"
  jobs:
  - job: TriggerTargetPipelines
    displayName: "Trigger target pipelines"
    steps:
    - ${{ each pipeline in parameters.TargetPipelines }}:
      - powershell: |
          $body = @{
            resources = @{
              repositories = @{
                "NuGetGallery" = @{
                  refName = "$(TargetRef)"
                }
              }
            }
          }
          $headers = @{ "Authorization" = "Bearer $env:ACCESS_TOKEN" };
          $url = "$(System.CollectionUri)$(System.TeamProject)/_apis/pipelines/${{ pipeline.id }}/runs?api-version=7.1"
          Invoke-RestMethod -Uri $url -Method POST -Headers $headers -Body ($body | ConvertTo-Json -Depth 10) -ContentType "application/json"
        displayName: "Trigger ${{ pipeline.name }}"
        env:
          ACCESS_TOKEN: $(System.AccessToken)
