// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Collections.Generic;

namespace NuGet.Services.Validation
{
    /// <summary>
    /// The response from starting or checking a validation step.
    /// </summary>
    public interface IValidationResponse
    {
        /// <summary>
        /// The status of the validation step.
        /// </summary>
        ValidationStatus Status { get; }

        /// <summary>
        /// The URL to the modified package content. This URL should be accessible without special
        /// authentication headers. However, authentication information may be included in the URL (e.g. Azure Blob
        /// Storage SAS URL). This URL need not have a single value for a specific <see cref="IValidationRequest.ValidationStepId"/>.
        /// </summary>
        string OutputUrl { get; }

        /// <summary>
        /// The results generated by the validation step. These provide additional information,
        /// such as debugging information or reasons for failure.
        /// </summary>
        IReadOnlyList<PackageValidationResult> Results { get; }
    }
}