
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT
{
	?u rdf:type ?z
}
WHERE
{
	?a rdfs:range ?z . 
	?x ?a ?u 
	FILTER(isURI(?u))
}
